### ISSUE TITLE
C2 is updated with payment receipt

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1004]
As an admin, I want the micropurchase system to update C2 automatically when a vendor has confirmed payment, so I don't have to do it manually. Also will help with Pagasys reporting as we'll have proof of payment receipt

- [ ] **Scenario: Auction marked as paid gets updated in C2**
- Given there is an auction
- And the auction has been successfully delivered
- And the vendor has been paid
- When the vendor confirms payment
- Then a payment receipt should be sent to C2

## Notes:
This could be as simple as updating C2 with some text or it may require a screenshot of something. @adelevie will follow up with Kathryn.

**Comment by mtorres253** [comment]
Spoke with Kathryn. She would prefer a screenshot. So, let's try to attach a screenshot of the admin status message - vendor confirmed payment  to the C2 request.

**Comment by jessieay** [comment]
wondering how we want to screenshot this -- if we add upload capability on our side, we will need to get AWS keys etc. Not terrible but a process to get that type of stuff. does it need to be an image, alan, or can it be something else?

**Comment by jessieay** [comment]
via slack:

so what you need is an image?
I am just trying to make sure we dont build something more complicated than we need

can we store BLOBs in the DB?

maybe? I mean if we are just sending it to them, we dont need to store it at all
but why if we are uploading an image, why not just upload it to c2 directly?

I am good with that

**Comment by jessieay** [comment]
Ok this is the new strategy:

create a receipt URL 

contains:
date of payment, amount paid, description of auction, name of vendor, email of vendor, vendor acknowledges receipt

update the C2 request to contain a link to this receipt when the payment is confirmed by the winning vendor

when purchaser goes to pegasus, they visit that URL and take a screenshot to upload

**Comment by jessieay** [comment]
Thinking of putting this in the "link to product" field in C2, then we can put the delivery URL in the "additional Info" area. thoughts @adelevie  ?

![screen shot 2016-08-18 at 4 21 06 pm](https://cloud.githubusercontent.com/assets/601515/17793917/e550ccfa-655f-11e6-943b-dd7dcaa0e858.png)

**Comment by jessieay** [comment]
(we currently put the delivery URL in that field, FYI)

**Comment by adelevie** [comment]
I'm ➕ on this strategy.

**Comment by jessieay** [comment]
Pieces of this feature:

1. Create a page at some URL like `auctions/:id/receipts/new` that has this info for that auction:

date of payment
amount paid
description of auction
name of vendor
email of vendor
vendor acknowledges receipt (true / false)

2. When we update the C2 request when an auction is accepted (`UpdateC2Proposal`), we include the above URL in the `delivery_url` field. 

3. Right now we include the auction's (delivery) pull request URL for the auction in the `delivery_url` field on C2, let's include that in `additional_info` instead

**Comment by jessieay** [comment]
This was closed via https://github.com/18F/micropurchase/pull/1109 (accidentally used waffle link instead of trello link on there so auto-closing didnt happen)
