### ISSUE TITLE
Vendor messaging - Auction show page - Need DUNS number to bid

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1007]
As a vendor, I want to know if there are factors preventing me from bidding on an auction so that if I want to bid on it, I can address those factors. So if I'm prevented from bidding on an auction because I don't have a DUNS number, then I should see that message

- [ ] **Scenario: Vendor sees "DUNS number needed" message on auction show page**
- Given I am a registered vendor
- And I am viewing an auction that is coming soon, or is open
- And I don't have a valid DUNS number
- When I go to the auction show page https://micropurchase.18f.gov/auctions/[id]
- Then no longer see the flash message reminder to update my duns number
- And I should see the following message in the status box

> Please update your profile
> Your profile must contain a valid DUNS number before you can place a bid. Please update your profile.

<img width="330" alt="screen shot 2016-08-03 at 7 10 47 pm" src="https://cloud.githubusercontent.com/assets/100149/17388042/048055cc-59ae-11e6-9c3f-4c4841f45aff.png">
 
- And "update your profile" should link to that vendor's profile

## Notes
- This story is to just move and update existing messaging so that it appears in the new status box 

- Status box should be at the top of the right hand column

<img width="1003" alt="screen shot 2016-08-03 at 7 11 36 pm" src="https://cloud.githubusercontent.com/assets/100149/17388054/29e37146-59ae-11e6-8bbd-df7a91f6d20c.png">

**Comment by jessieay** [comment]
WIP version of this here https://github.com/18F/micropurchase/compare/jy-need-duns-to-bid?expand=1
