### ISSUE TITLE
Admin messaging - Auction show page - Reject work

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1015]
As an admin, I want a way to easily mark an auction as rejected, without having to go into the edit form. So I should be able to do this on the show page of an auction

- [x] **Scenario: Admin marks an auction as rejected from the show page**
- Given I am an authenticated admin
- And a vendor has delivered code for an auction (clicked the "I'm Done" button)
- When I view the show page for that auction
- Then I should see the following messaging in the status box

> Pending acceptance
> [auction.winner] made a pull request and marked this auction as having been delivered. If their work meets this auction’s acceptance criteria, click “accept.” Otherwise, click “reject.”

- And I should see an "Accept" and a "Reject" button
- And "[Auction.Winner]" should link to the winning vendor's profile (https://micropurchase.18f.gov/admin/users/[id])
- And "pull request" should link to the Delivery URL for that auction

<img width="334" alt="screen shot 2016-08-08 at 6 45 48 am" src="https://cloud.githubusercontent.com/assets/100149/17482161/55612680-5d35-11e6-8115-c3fc4a094701.png">

- [x] **Scenario: Admin clicks "reject" button on auction show page**
- Given I am an authenticated admin
- And I am on the show page for an auction that has work delivered (the vendor has clicked "I'm Done")
- When I click to the "Reject" button
- Then the auction should be marked as rejected by me
- And I should see the following messaging in the status box

> Rejected
> [Vendor.name]'s work was rejected on [auction.rejectionDate].

- And "[Vendor.name]'s work" should link to the delivery URL

## Notes

- Status box appears at the top right of the auction show page

<img width="992" alt="screen shot 2016-08-08 at 6 59 48 am" src="https://cloud.githubusercontent.com/assets/100149/17482248/bc1daad8-5d35-11e6-8c60-c0bea497f373.png">

**Comment by andrewmaier** [comment]
I believe we spoke yesterday about creating a separate status if the person who rejected this work is viewing it? The current copy is

>[RejectingAdmin] rejected [auction.winner]’s bid on [auction.rejectionDate].

@mtorres253 I believe you asked to split this into 
> You rejected ...
and 
> Someone rejected

Let me know what you decide and I can update the prototype/workflows.

**Comment by jessieay** [comment]
waiting for merge of #1003 before I start on this
