### ISSUE TITLE
Auction show page - style clean-up

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1032]
Let's do a few things to clean up the auction show page styles

this is for both micropurchase.18f.gov/auctions/[id]

and for  micropurchase.18f.gov/admin/auctions/[id]

- Replace ribbon with status label

- The status label colors should be the same as the colors on the auction preview tiles
![Uploading Screen Shot 2016-09-02 at 3.21.51 PM.png…]()

- Move edit button to top right corner (admins only)

- Get the layout as close as you can to the layout in the prototype

- Try to match font sizes, line spacing and colors

- Move from button nav to tab nav

https://pages.18f.gov/micropurchase/auctions/show/?auctionWorkflowState=draft-vendors

**Comment by jessieay** [comment]
moving this to backlog until there are more details
