### ISSUE TITLE
Small typo on "hero" dashboard!

### ISSUE THREAD

**Issue by epugh** [18F/micropurchase#1035]
Checking out the https://micropurchase.18f.gov/insights site, and noticed a small typo.  Poked around to see if it was an obvious typo in code versus data, but didn't get to a "found it" point.  

Nice clean Rails code!

![18f - micro-purchase 2016-08-11 07-15-10](https://cloud.githubusercontent.com/assets/22395/17587048/aa727c22-5f93-11e6-8453-368b5841ecd7.png)

**Comment by adelevie** [comment]
Thanks, @epugh!

PR is here: https://github.com/18F/micropurchase/pull/1036

I'll merge ASAP.
