### ISSUE TITLE
Site is crashing/performing very slowly

### ISSUE THREAD

**Issue by adelevie** [18F/micropurchase#1040]
I suspect this is partially due to the `/insights` page.

From @jessieay:

```
app.crash {"instance"=>"[redacted]", "index"=>0, "exit_status"=>255, "exit_description"=>"out of memory", "reason"=>"CRASHED"}
```

**Comment by jessieay** [comment]
One way to address this would be fragment caching on our page stats: http://guides.rubyonrails.org/caching_with_rails.html#fragment-caching

Or, we could just load each stat into a postgres table. one column could be the auction count and when that changed we would re-calculate the stats...

**Comment by adelevie** [comment]
attempt: https://github.com/18F/micropurchase/pull/1041
