### ISSUE TITLE
Make seeds indempodent

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#1067]
We should be able to run seeds on an existing database and not get any errors (this is not the case right now because of some uniqueness validations)

**Comment by harrisj** [comment]
See also #1083 as a related issue. We might want to just do skill population in seeds and remove the faker-driven auctions like that issue proposes.

**Comment by jessieay** [comment]
This is closed via https://github.com/18F/micropurchase/pull/1072 but we will continue to work to improve our seeds
