### ISSUE TITLE
add dev:prime task

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#1083]
right now we are using the seeds file to add dev data. seed data should be for a prod database. let's add that data to another task instead and just add a few skills or something to seeds.rb

**Comment by harrisj** [comment]
I am trying so hard to avoid pasting an Optimus Prime GIF in this discussion

**Comment by jessieay** [comment]
example task in Dolores rails app: https://github.com/18F/dolores-landingham-slack-bot/blob/master/lib/tasks/dev.rake
