### ISSUE TITLE
Insights page shows numbers twice

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1101]
To duplicate

Navigate to https://micropurchase.18f.gov/insights

Expected behavior:
In the Insights section I should only see one each of the metrics

Actual behavior: the metrics appear twice each

![screen shot 2016-08-24 at 1 38 47 pm](https://cloud.githubusercontent.com/assets/100149/17947118/1fc749d2-6a00-11e6-9c7f-f1cdfb5dd48d.png)

**Comment by jessieay** [comment]
weird, I have no idea why that happened. Our nightly task is supposed to destroy all of the existing stats and re-build based on current database numbers. Just ran it manually and all is good now.

Will keep my eye on this to see if it happens again, but for now it is fixed.

GOOD NEWS: looks like savings stat has gone down, https://github.com/18F/micropurchase/issues/1037 (used to be $65k)

**Comment by jessieay** [comment]
ok happened again last night. This PR should fix it: https://github.com/18F/micropurchase/pull/1110
