### ISSUE TITLE
C2 integration failing?

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1106]
To duplicate:

Go to https://micropurchase.18f.gov/admin/auctions/33

Expected behavior
I should see the following messaging

> Pending C2 approval
This auction has been sent to C2 for approval. You can check the status of this approval here.

Actual behavior:
I see the following messaging

> Pending C2 approval
This auction has been sent to C2 for approval. 

Notes: 
The C2 proposal URL exists but I still see the Pending C2 approval message (without the "here" link)

https://cap.18f.gov/proposals/5351

Same thing is happening on https://micropurchase.18f.gov/admin/auctions/29

**Comment by jessieay** [comment]
Pr to fix this: https://github.com/18F/micropurchase/pull/1121

was not a bug in C2 integration, was an error on our end. We were accidentally flipping the statuses of "sent to c2 but no URL yet" and "sent to c2 and we have a URL but not approved yet"
