### ISSUE TITLE
List Font Weights are different than normal p weights

### ISSUE THREAD

**Issue by lauraGgit** [18F/micropurchase#1107]
in auctions, lists do not have bullets so it looks odd that they are a different font weight than the text that is in a p tag.

**Comment by andrewmaier** [comment]
Hey @lauraGgit this is something we're addressing in [the updated design](https://pages.18f.gov/micropurchase/auctions/show/?auctionWorkflowState=coming-soon-vendors) — see [this](https://pages.18f.gov/micropurchase/docs/getting-started/) content-heavy page, for example. It's just going to take us some time to migrate these over to production :)

**Comment by mtorres253** [comment]
Let's try updating the USWDS so that we can fix this bug.

**Comment by jessieay** [comment]
WIP here https://github.com/18F/micropurchase/compare/jy-test-uswds-fonts?expand=1
