### ISSUE TITLE
As an admin, I need the 18F and DAP Google Analytics codes to track visitors. 

### ISSUE THREAD

**Issue by allalala** [18F/micropurchase#114]

**Comment by jackiekazil** [comment]
@allalala is there a url for this project?

**Comment by allalala** [comment]
@jackiekazil the URL is https://micropurchase.18f.gov/ (we're waiting on formal ATO next week)

**Comment by jackiekazil** [comment]
The info that you need here (about 18F & DAP):  https://github.com/18F/analytics-standards

Here is the 18F snippet for you w/ unique UA code.... 
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48605964-40', 'auto');
  ga('set', 'anonymizeIp', true);
  ga('set', 'forceSSL', true);
  ga('send', 'pageview');
</script>
```

I will let you take it from here. :-) Let me know if you have any questions.

**Comment by allalala** [comment]
thank you @jackiekazil. Assigning to @adelevie for implementation.

**Comment by allalala** [comment]
This is complete
