### ISSUE TITLE
Profile page should link to getting-paid in context, not faq

### ISSUE THREAD

**Issue by tmcw** [18F/micropurchase#1151]
https://micropurchase.18f.gov/profile

In the sentence

> Before we can pay you, we'll need a location we can visit to issue payment. If you're unfamiliar with processing payments online, see our guide for more information.

The link points to https://micropurchase.18f.gov/faq

But https://pages.18f.gov/micropurchase/docs/getting-paid/ appears to be the more specific page on the the discussed topic.

**Comment by mtorres253** [comment]
Thanks @tmcw will add this to the backlog. The pages site is just a prototype. We're moving from that content to the live site hopefully in the next sprint.

**Comment by mtorres253** [comment]
Hi @tmcw We fixed it! https://micropurchase.18f.gov/profile
