### ISSUE TITLE
Consolidation of logic in BidStatusPresenter/AdminAuctionStatusPresenter classes

### ISSUE THREAD

**Issue by harrisj** [18F/micropurchase#1167]
Per the comments on #1159, there is some redundancy between the BidStatusPresenter::*::Admin classes and AdminAuctionStatusPresenter classes. I think @jessieay makes a very good point on this, but I would like to make this the subject of a future PR. It seems like we could 

1. Migrate some of the functionality in the AdminAuctionStatusPresenter classes (i18n, action_partial) to their equivalents/new classes in BidStatusPresenter
2. Eliminate the AdminAuctionStatusPresenter hierarchy entirely

Thoughts?

**Comment by jessieay** [comment]
right now https://github.com/18F/micropurchase/blob/develop/app/presenters/admin_auction_status_presenter/future_published.rb and https://github.com/18F/micropurchase/blob/develop/app/presenters/bid_status_presenter/future/admin.rb are returning the same content -- can we fix that in this PR and keep the rest of the changes for some future time?

**Comment by jessieay** [comment]
@harrisj did you intend #1199 to close this or do we want to do more work on it?

**Comment by harrisj** [comment]
I guess that is fine since we aren't eliminating the AdminAuctionStautsPresenter hierarchy. I haven't renamed any C2StatusPresenters

**Comment by jessieay** [comment]
works for me - closing
