### ISSUE TITLE
New copy for Policies page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1170]
As a vendor or potential customer, I want to have a clear and thorough description of the platform policies somewhere on the micropurchase site, so that I can reference it when I have questions.

- [x] **Scenario: Visitor navigates to /policies/ page and sees micropurchase policies**
- Given I am a visitor
- When I go to this URL: https://pages.18f.gov/micropurchase/policies/
- Then I should see this content
https://pages.18f.gov/micropurchase/policies/

**Comment by jessieay** [comment]
@mtorres253 what do you want the URL to be on the micropurchase site? currently you have it as https://pages.18f.gov/micropurchase/policies/, which is a typo

**Comment by jessieay** [comment]
also update "creating an auction" page for this story https://github.com/18F/micropurchase/issues/1175#issuecomment-246782645
