### ISSUE TITLE
New page - How to get paid

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1172]
As a visitor to the site, I want to know how vendors get paid, so that I can make sure my profile is set up properly, and I know what to expect in terms of payment for auctions I win.

 Scenario: Visitor navigates to /docs/getting_paid/ page
Given I am a visitor go the micro-purchase site
When I go to this URL: micropurchase.18f.gov/docs/getting_paid/
Then I should see this content https://pages.18f.gov/micropurchase/docs/getting-paid/

**Comment by adelevie** [comment]
Should these docs live on the micropurchase.18f.gov domain or on pages.18f.gov?

**Comment by mtorres253** [comment]
hi @adelevie they live on the micropurchase site. this story is to create that page
