### ISSUE TITLE
New Page - Getting Started

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1174]
As a visitor to the site, I want to know how to get started with micropurchase (what I need to do to participate), so there should be a page on the site that provides that information

- [ ] **Scenario: Visitor clicks navigates to /docs/getting_started/**
- Given I am a visitor to the site
- When I navigate to micropurchase.18f.gov/docs/getting_started/
- Then I should see this content on that page: https://pages.18f.gov/micropurchase/docs/getting-started/

**Comment by jessieay** [comment]
once this is done, add link to about page (see https://github.com/18F/micropurchase/issues/1161)
