### ISSUE TITLE
New page - Creating an auction

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1175]
As a visitor to the site, I want to know the details around how to create an auction that is likely to be successful, so there should be a page where I can get that information

- [x] **Scenario: Visitor navigates to /docs/creating_an_auction/ page**
- Given I am a visitor to the micropurchase site
- When I navigate /docs/creating_an_auction/
- And I should see this content on that page: https://pages.18f.gov/micropurchase/docs/creating-an-auction/

**Comment by jessieay** [comment]
this page links to the policies page. leaving that link out until https://github.com/18F/micropurchase/issues/1170
