### ISSUE TITLE
Vendor messaging - auction show page - bid is above maximum bid

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1178]
- [ ] **Scenario: Vendor submits bid over the maximum bid - sealed-bid**
- Given that I am an authenticated vendor
- And there is a sealed-bid auction
- And I'm eligible to bid on it
- And I have NOT bid on the auction
- And I am on the auction show page
- And I have entered a bid amount in the bid box that is larger than the maximum bid
- When I click the "Place Bid" button
- Then my bid should not be saved
- And I should not see the javascript confirmation
- And the page should reload
- And the status box should contain the following messaging

> Bid rejected
> Amount was not accepted. Please enter a whole number less than $[auction.startingBid].

- And I should still see the Place Bid button and the "Amount" input

<img width="331" alt="screen shot 2016-08-08 at 2 50 38 pm" src="https://cloud.githubusercontent.com/assets/100149/17491898/85f38fee-5d77-11e6-8406-674b178f5e10.png">

## Notes
This implies removing the current flash message.

**Comment by harrisj** [comment]
I would like to do this as a general case for any error returned by BidStatusValidator and maybe give those errors a title and message.
