### ISSUE TITLE
Design cleanup: Header nav has link to "Account" instead of links to "Profile" and "My Bids"

### ISSUE THREAD

**Issue by andrewmaier** [18F/micropurchase#1193]
Topnav for both vendors and admins should have a link labeled "Account" instead of the current "Profile" and "My Bids" links.

Clicking on the "Account" link in the header goes to /account/profile. Details of what is on that page are in #1201 and #1330

**Comment by mtorres253** [comment]
I'll have to write new features for the /payments-received/ and the /deliveries-rejected/ content (including the default message)
