### ISSUE TITLE
Design cleanup: Auctions home

### ISSUE THREAD

**Issue by andrewmaier** [18F/micropurchase#1194]
- See [this vignette](https://docs.google.com/document/d/1lWPYtQLdyZ42ENPIMxITcAuALXr2ADswu0XUCB7hYb4/edit#heading=h.553wlv2hs1ya) and [the prototype's homepage](https://pages.18f.gov/micropurchase/).

- “Auctions” title should be bigger, lighter weight (font-weight: 300) Change font to meriweather
- Coming soon badge, should use lowercase on “soon,” have rounded edges.
- Pagination should also better reflect the prototype styles:
![image](https://cloud.githubusercontent.com/assets/2970/18362725/f3812dbc-75d4-11e6-9d1a-905fff556e8c.png)

**Comment by mtorres253** [comment]
We decided to leave it as "all" (rather than open and coming soon) in a previous grooming session. Let's revisit

**Comment by jessieay** [comment]
had a ? for @mtorres253 on this in slack: https://18f.slack.com/archives/micropurchase-dev/p1475016909001041

**Comment by mtorres253** [comment]
Per discussion with @jessieay we are getting rid of the "all" tab in the "Auctions" section of the admin view. We now have just "Needs attention" and "Closed". The "all" view will be collapsed with /auctions, and edit button will be viewable by admins only
