### ISSUE TITLE
Admin messsaging - Auction show page - Payment needed using 18F p-card

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1197]
Given I am an admin managing auctions, if an auction has been accepted, and 18F needs to pay for it, I should see the messaging reflecting that status in on the auction show page

- [ ] **Scenario: Admin sees that accepted auction requires payment via 18F p-card**
- Given I am an authenticated admin
- And there is an auction using the default 18F p-card
- And the auction has been accepted
- And there is a payment URL for the winning vendor on file
- When I navigate to the show page for that auction
- Then I should see the following message in the status box

> Pending payment from 18F
> The p-card holder has been asked (via C2) to remit payment. 

- And "C2" should link to the C2 proposal URL for that auction

**Comment by harrisj** [comment]
Upon discussion, decided this is a modification to the existing "Accepted" text for admins
