### ISSUE TITLE
As an admin, I want to manage data...

### ISSUE THREAD

**Issue by blacktm** [18F/micropurchase#12]
Given I'm authenticated as an admin (could be anyone in [consulting group](https://github.com/orgs/18F/teams/consulting)),
I can manage any models in the database via CRUD operations.

**Comment by adelevie** [comment]
As an admin,
I want to sign in without being asked to provide a DUNS or SAM number,
So that I don't enter un-needed information.

**Comment by adelevie** [comment]
As an admin
I want to be able to visit the `/admin` routes
So that I can view admin-only content and make admin-only transactions.

**Comment by adelevie** [comment]
As an admin
I want to be able to view a list of unverified bidders who have added their DUNS/SAMS numbers
So that I can verify them.

**Comment by adelevie** [comment]
As an admin
I want to be able to receive email from users
So that I can respond to their needs.

**Comment by blacktm** [comment]
This is the same as #54.
