### ISSUE TITLE
Admin messaging - Auction show page - Ready for Work

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#1207]
As an admin, I want to know when an the winner of an auction has been selected but the winner has not yet started work, so there should be some messaging in the status box to that effect

- [ ] **Scenario: Admin views status message on auction show page that winning vendor has not yet started work**
- Given I am an authenticated admin
- And there is a published auction (using default p-card or other)
- And the auction has ended 
- And there is a winner
- And the winner has not yet started work
- When I am on the show page for that auction (micropurchase.18f.gov/admin/auction/[id])
- Then I should see the following messaging in the status box

> Ready for work
> [auction.winner] won this auction on [auction.winDate] with a bid of $[auction.winBid]. They’ve received an email letting them know the delivery deadline ([auction.deliveryDeadline]) and how to get started.

![screen shot 2016-09-13 at 4 16 11 pm](https://cloud.githubusercontent.com/assets/100149/18494795/787d6e12-79cd-11e6-843e-add6e39fcbbf.png)

## Notes
Start without the "email" link. Use github name for auction.winner

In this case, the winning vendor does have a payment URL but has not submitted a delivery URL yet (so the auction is not considered a "work in progress" yet

**Comment by mtorres253** [comment]
Ok to resume @adelevie

**Comment by mtorres253** [comment]
Hello @adelevie should @harrisj take this over?
