### ISSUE TITLE
Switch bid amounts away from floats?

### ISSUE THREAD

**Issue by harrisj** [18F/micropurchase#121]
Developers are generally [advised against representing currency amounts as floats](http://spin.atomicobject.com/2014/08/14/currency-rounding-errors/). The issue is that rounding errors may mess up comparisons between two equivalent amounts or subtle rounding issues may occur when there are many calculations. These concerns might be more academic than real for micropurchase: there are at most 6 significant digits in our amounts and no derived calculations, but I wanted to raise the issue for discussion.

There is a [Money-rails](https://github.com/RubyMoney/money-rails) gem than encapsulates some good practices for representing currency in Rails projects, but that is too heavyweight for our purposes (we don't need to do currency conversions for instance). I'd instead suggest that we either do one of two following things:

1. Convert the currency fields in the database to `DECIMAL(15, 2)` instead of `float`. ActiveRecord would dereference into `BigDecimal` objects automatically, but we might need to verify that we are using that type in PlaceBid objects, etc too.
2. Switch to using integers instead. Since we might want to support bidding at the cent level, this would mean changing fields like `amount` to be `amount_cents` and adding `amount` and `amount=` on the model to divide and multiply by 100 as appropriate.

The second approach is the one taken by the Money gem, and it seems like a little more work but it avoids any floats or float-like wrappers. What do you think? Is this something to worry about? Should we change it?

**Comment by adelevie** [comment]
The second approach seems the most elegant. I'm not sure how worried we should be, but that's not because of skepticism, it's just that I don't know!

**Comment by harrisj** [comment]
Since we are not allowing sub-dollar bids anyway, we could just switch over to using ints in the DB without changing much functionality in the app. Then when we want to move to sub-dollar bids, we could do the change over to the `_cents` approach (and multiply all existing bids by 100)

**Comment by harrisj** [comment]
Fixed in pull request #156
