### ISSUE TITLE
Add hound or other style-checking CI?

### ISSUE THREAD

**Issue by harrisj** [18F/micropurchase#122]
I wanted to see if we felt comfortable adding [Rubocop](https://github.com/bbatsov/rubocop)-based style checking to this project. I've found it very useful, especially since I have a linter in my editor that reports on style violations. There are several options we could consider:

- Use a service like [Hound](https://houndci.com/) which is a CI for code style-checking that will comment on individual style violations in any github PR/branch (this can lead to a bunch of emails, so it's sometimes really annoying)
- Modify the rake task that is run by Travis to also run Rubocop and fail if it finds any style violations. This means far less emails/comments, but it sometimes means encapsulating sections of code with directives for Rubocop to ignore that part which isn't particularly elegant.
- Leave the style compliance optional for now. Maybe add a rake task for running rubocop and a rubocop.yml config for specific issues, but don't mandate compliance.

Note that the default rubocop.yml often has some settings we might want to tweak (those on maximum line length or method length or such). We should see if another project has a preferred one we can use already if we decide to do this.

**Comment by vzvenyach** [comment]
I don't know what hound or rubocop provide, but code climate may handle this out of the box. Certainly does for Python.

**Comment by harrisj** [comment]
Oh, it looks like it does! https://github.com/codeclimate/codeclimate-rubocop

Should we try enabling it?

**Comment by harrisj** [comment]
So, @adelevie and @vzvenyach. Do you think we should enable Hound CI on this? Or should we try the Rubocop within CodeClimate?

**Comment by allalala** [comment]
@harrisj this is OK to close, correct?

**Comment by harrisj** [comment]
Well, we aren't doing any sort of enforcement on style compliance for pull requests. CodeClimate is [including Rubcop issues to calculate the project's GPA](https://codeclimate.com/github/18F/micropurchase/issues), but that's about it. Every so often I go in and do cleanup PRs to fix some issues when the score declines. The question is should we have Travis fail if you have Rubocop issues and you haven't fixed them (or disabled Rubocop around that section of code). I'm not sure we should.

**Comment by harrisj** [comment]
I think we should close this issue, since apparently CodeClimate can also report on stylistic issues in PR if we enable it.
