### ISSUE TITLE
Add enum to represent "accepted but no payment url"

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#1222]
Right now, we just look at whether there is an `accepted_at` timestamp (that is not set if the winner doesnt have a payment URL). That is confusing and could be clarified with an enum under `status`

**Comment by jessieay** [comment]
see https://github.com/18F/micropurchase/pull/1221#discussion_r78751741 for more context

**Comment by harrisj** [comment]
I approve of this approach

**Comment by harrisj** [comment]
I almost feel like this should be another `c2_status` to be honest

**Comment by jessieay** [comment]
This state could exist for either purchase card.
