### ISSUE TITLE
FAQ page missing info about payment URL

### ISSUE THREAD

**Issue by mscottford** [18F/micropurchase#1228]
The profile page has this copy for the payment URL box:

> Before we can pay you, we'll need a location we can visit to issue payment. If you're unfamiliar with processing payments online, see [our guide for more information](https://micropurchase.18f.gov/faq).

But the linked FAQ page does not have any information about payment URLs or what's expected to appear on them. I'm guessing that what's needed to appear at that URL is a form to specify a payment amount and credit card details, but I wasn't sure if there were any other requirements that I might be overlooking.

This came up as I'm working on creating a payments page on my site to provide this capability.

I'm happy to open up a PR to revise the FAQ to include this info, and I thought it'd be best to validate my assumptions first.

**Comment by jessieay** [comment]
Hello! 

Thank you for reporting this.

We are going to be updating that page soon, but I also just updated the link in this PR: https://github.com/18F/micropurchase/pull/1229


It now links to https://micropurchase.18f.gov/docs/getting_paid, which links to the profile page.

Does that solve this issue?

**Comment by mtorres253** [comment]
Looks like this has been addressed with #1229
