### ISSUE TITLE
Vendor messaging - Auction show page header - bid status - closed sealed bid

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1269]
As a vendor, I want to see the starting bid for sealed bid auctions so that I know where to start! (Currently the auction show page shows "Current bid:" with no bid. So we should change that)

- [ ] **Vendor/visitor sees winning bid and winning vendor name in header of show page for open sealed-bid auctions**
- Given I am a visitor to the micro-purchase site
- And there is a sealed bid auction
- And that auction is published
- And that auction has ended
- And the auction has a winning bid
- When I go the auction show page for that auction (micropurchase.18f.gov/auctions/[id])
- Then I should see a section in the header labeled "Winning bid:" 
- And in that section I should see the winning bid for that auction
- And I should see the winning vendor name (or GitHub name) in parentheses after the bid

## Notes
Use the styles referenced below (or as close as you can get)

![screen shot 2016-09-20 at 4 45 37 pm](https://cloud.githubusercontent.com/assets/100149/18838166/069fd196-83cc-11e6-8ec8-cb60ca178047.png)

**Comment by harrisj** [comment]
This already exists

**Comment by mtorres253** [comment]
Looks like this is working as expected
