### ISSUE TITLE
Admin can archive auction

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1276]
So I have a situation where I have a draft auction that has C2 approval, but is not going forward. I have another situation where we will eventually go forward with the auction but the current C2 approval can't be used because the IAA expires this week and we don't have all the details yet for the auction.

As an admin user, I want to archive draft auctions that aren't going forward so they don't remain in a draft state forever.

**Context**
- Given I am an authenticated admin
- And there is an unpublished auction

- [x] **Scenario: Admin archives draft unpublished auction with no bids**
- When I go to the auction page
- Then I should see a way to archive that auction

- [x] **Scenario: Admin cannot archive published auctions**
- When I go to the auction page
- Then I should NOT see a way to archive that auction

- [x] **Scenario: Admin sees confirmation before archiving an auction**
- And I am on the edit page for that auction
- When I click on the "Archive auction" link
- Then I should see a confirmation with the following message

> Are you sure you want to archive this auction?

- And I should see a "Confirm" button
- And I should see a "Cancel" button

- [x] **Scenario: Admin confirms that auction should be archived**
- When I click on the "Confirm" button
- Then the auction should be archived
- And I should navigate to the auction show page (micropurchase.18f.gov/admin/auctions/[id])
- And the status box copy should read:

> Archived
> This auction was archived on [date]

- [x] **Scenario: Admin cancels out of archive confirmation**
- When I click on the "Cancel" button
- Then the confirmation dialog should disappear
- And I should remain on the edit auction page

## Notes
Archive button is on the edit form. Easy way to implement this would be to make the archive a soft delete using something like the paranoia gem.

**Comment by harrisj** [comment]
So, I am a bit biased against paranoia, since that involves some *magic* and default scopes. I am inclined to instead add a new `archived` state to delivery_status and make sure that published scope does not include archived auctions. We could also include an archived_at time if you want

**Comment by harrisj** [comment]
Because he wants to see Archived auctions in #1304, we should avoid any approach that changes the default_scope

**Comment by harrisj** [comment]
Oh never mind, Paranoia lets you find them
