### ISSUE TITLE
Admin and Vendor messaging - Auction show page header - Starting price for auctions that are coming soon

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1292]
As a vendor or a visitor, I want to see the starting price of auctions that are coming soon so I can decide whether I want to bid on that auction.

- [x] **Vendor/visitor sees starting price in header of show page for auctions that are coming soon**
- Given I am a visitor to the micro-purchase site
- And there is a reverse auction
- And that auction is published
- And that auction has not yet started
- And the auction has no bids
- When I go the auction show page for that auction (micropurchase.18f.gov/auctions/[id]) or (micropurchase.18f.gov/admin/auctions/[id])
- Then I should see a section in the header labeled "Starting price:" 
- And in that section I should see the starting price of that auction

## Notes
Use the styles referenced below (or as close as you can get)

![screen shot 2016-09-20 at 4 45 37 pm](https://cloud.githubusercontent.com/assets/100149/18838166/069fd196-83cc-11e6-8ec8-cb60ca178047.png)

**Comment by harrisj** [comment]
Do we want the language to say "Starting bid" and not "Current bid"?

**Comment by mtorres253** [comment]
Yes, sorry @harrisj the mock is incorrect. "Starting price" is correct.

**Comment by harrisj** [comment]
Yep, I should've read more closely. Also, you want this bid label on the admin view I see. We currently don't have that functionality, but I don't see why not to add it.
