### ISSUE TITLE
Admin and vendor messaging - Auction show page - Winning bid for closed auctions

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1293]
As an admin or a vendor, I want to quickly see the winning bid for any auction, so if I am viewing the show page of an auction, the winning bid should be shown to me.

- [x] **Admin and Vendor/visitor sees winning bid and winning vendor name in header of show page for closed auctions**
- Given I am a visitor to the micro-purchase site
- And there is an auction (reverse or sealed-bid)
- And that auction has ended
- And the auction has a winning bid
- When I go the auction show page for that auction (micropurchase.18f.gov/auctions/[id]) or (micropurchase.18f.gov/admin/auctions/[id])
- Then I should see a section in the header labeled "Winning bid:" 
- And in that section I should see the winning bid for that auction
- And I should see the winning vendor name (or GitHub name) in parentheses after the bid

## Notes
Use the styles referenced below (or as close as you can get)

![screen shot 2016-09-20 at 4 45 37 pm](https://cloud.githubusercontent.com/assets/100149/18838166/069fd196-83cc-11e6-8ec8-cb60ca178047.png)

**Comment by harrisj** [comment]
Currently this is 
> "Winning bid (#{lowest_bidder_name}): #{highlighted_bid_amount_as_currency}"

**Comment by harrisj** [comment]
This already exists 
![18f_micro-purchase_-_reactive_3rd_generation_installation](https://cloud.githubusercontent.com/assets/2044/19130900/471724b2-8b1b-11e6-8ab0-9c28ce4f2930.jpg)

**Comment by mtorres253** [comment]
Looks like this is working as expected
