### ISSUE TITLE
Admin view - Status box on auction show page - Finish work

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1299]
As an admin, I want to be able to mark an auction as done if a vendor forgets to do that themselves, so there should be a way for me to do this in the UI

- [x] **Scenario: Admin sees "Mark as delivered" button in status box of auction show page"
- Given I am an authenticated admin
- And there is a published auction that has a winner
- And there is a delivery URL specified
- And the vendor has not yet clicked the "I'm done" button
- When I go to the auction show page for that auction
- Then I should see the following status in the status box

> Work in progress
> [auction.winner.name] initiated a pull request on [auction.startWorkDate], and should complete work no later than [deadline].

- And I should see a "Mark as delivered" button

![screen shot 2016-09-26 at 3 00 42 pm](https://cloud.githubusercontent.com/assets/100149/18849774/299ce804-83fa-11e6-8d80-229f6ce49dcf.png)

- [x] **Scenario: Admin clicks "Mark as delivered" button and delivers auction"
- When I click on the "Mark as delivered" button
- Then the auction should be marked as done
- And the vendor should no longer be able to mark it as done

**Comment by harrisj** [comment]
Just so I'm clear, this is an update for the work originally in #1157, right?
