### ISSUE TITLE
Archived auctions show up on "Closed" page of "Auctions" section

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1304]
So that I have a clear record of all archived auctions, I should see any archived auctions listed on the "Closed" auction page of the "Auctions" section

- [x] **Scenario: Admin sees archived auction section on closed auctions page**
- Given I am an authenticated admin
- And there are archived auctions
- When I go to the "Closed" section of the "Auctions" page
- Then I should see a section labeled "Archived"
- And in this section I should see a table listing all archived auctions
- And the table should contain a column labled `<column label>`
- And the value in that column should be `<collumn data>`.

| Column Label | Column Data |
| ------- | ------- |
| Auction Title | Title of auction |
| Archived date | Date auction was archived |

- And the auction title should link to that auction show page

**Comment by harrisj** [comment]
We don't have the `archived_at` for the table here
