### ISSUE TITLE
Data for archived auctions does not get included on the insights page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1305]
As a visitor, I want to see accurate metrics on the insights page, so data for archived auctions should not appear on that page

- [ ] **Scenario: Archived auctions are not included in stats**
- Given I am a visitor to the site
- And there are archived auctions
- When I view the Insights page
- Then I do not see any data for archived auctions

**Comment by harrisj** [comment]
Currently, I have archived as another value for the `published` field (ie, an auction can be unpublished, published or archived). Since stats are only for published archives, this should not be a problem

**Comment by jessieay** [comment]
+1 to @harrisj -- I code reviewed archive stuff, and archived auctions will not be included in insights. closing this.
