### ISSUE TITLE
Is it 'micropurchase' or 'micro-purchase'? 

### ISSUE THREAD

**Issue by khandelwal** [18F/micropurchase#134]
There's a difference on the homepage.

**Comment by khandelwal** [comment]
<img width="1040" alt="screen shot 2015-12-18 at 1 43 20 pm" src="https://cloud.githubusercontent.com/assets/636752/11904341/80637104-a58d-11e5-90d4-7a224ccc2d94.png">

**Comment by khandelwal** [comment]
<img width="664" alt="screen shot 2015-12-18 at 1 45 00 pm" src="https://cloud.githubusercontent.com/assets/636752/11904354/8cafb97c-a58d-11e5-91d0-91c45df9f619.png">

**Comment by allalala** [comment]
Deferring to @vzvenyach, as product owner. 
I'm team #OneWord

**Comment by vzvenyach** [comment]
Technically, it's "micro-purchase" per the FAR.

**Comment by khandelwal** [comment]
I'm on team #oneworld with @allalala

**Comment by adelevie** [comment]
So ... what are my orders?

**Comment by allalala** [comment]
For branding reasons, I think one word sounds and looks better. It also eliminates confusion re: not adding a hyphen in the URL

**Comment by awfrancisco** [comment]
We use micro-purchase in all communications. Definitely think it should be standardized to one spelling.

**Comment by allalala** [comment]
it's micro-purchase :white_check_mark:
