### ISSUE TITLE
Collapse the fat footer 

### ISSUE THREAD

**Issue by khandelwal** [18F/micropurchase#135]
The two band footer looks pretty fat. I think bringing the 18F logo on the same line as the other footer elements will make this easier. 

<img width="1242" alt="screen shot 2015-12-18 at 1 55 21 pm" src="https://cloud.githubusercontent.com/assets/636752/11904595/0e4efece-a58f-11e5-8706-5f6f99ff0ace.png">

**Comment by khandelwal** [comment]
I would also change 'Email us' to be the actual email address - I think that's more clarity.

**Comment by allalala** [comment]
+1

**Comment by allalala** [comment]
Sending this on over to @harrisj and @adelevie for implementation.

**Comment by allalala** [comment]
@adelevie am I correct in understanding that this is complete? If so, feel free to close the issue.

**Comment by allalala** [comment]
@adelevie @harrisj this is :white_check_mark:, right?
