### ISSUE TITLE
Publish button is showing up twice

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1359]
To duplicate: 
Go to https://micropurchase.18f.gov/admin/auctions/37

Expected behavior: Publish button shows up once

Actual behavior: Publish button shows up twice

![Uploading Screen Shot 2016-10-11 at 1.11.31 PM.png…]()

**Comment by harrisj** [comment]
Here's a pic of the bug

![banners_and_alerts_and_localhost_3000_admin_auctions_1](https://cloud.githubusercontent.com/assets/2044/19356752/da9d3916-913c-11e6-901b-8c85f4a656ca.jpg)
