### ISSUE TITLE
Login banner is too obvious

### ISSUE THREAD

**Issue by khandelwal** [18F/micropurchase#136]
The login warning on the main page: 

<img width="1053" alt="screen shot 2015-12-18 at 2 40 14 pm" src="https://cloud.githubusercontent.com/assets/636752/11905601/61e54ca4-a595-11e5-8d28-93fdc1894803.png">

has a giant warning symbol for "Please login". 

Why not move that to the actual place someone can submit a bid? As a person who's interested, if I'm just browsing - I shouldn't need to login. At the point of bidding is the more appropriate time to prompt for a login.

**Comment by allalala** [comment]
@khandelwal I think this has been addressed by @ddotrollins and @brethauer's work.

**Comment by allalala** [comment]
![image](https://cloud.githubusercontent.com/assets/6518236/13274969/d457998c-da7d-11e5-8c96-17f845803605.png)
