### ISSUE TITLE
Admin can manually add C2 link

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1368]
As an admin, if C2 integration is broken, I want to be able to move an auction through the approval flow manually so that I can publish it!

- [ ] **Scenario: After request for C2 approval is made, and before the C2 request is set up, I see an input to manually enter C2 URL**
- Given I am an authenticated admin
- And there is a draft auction
- And I have clicked the "Request Approval" button
- And a C2 URL has not been detected by the system yet
- Then I see a text input in the status box labeled "C2 Proposal URL"
- And a button labeled "Set C2 URL"

- [ ] **Scenario: Admin manually enters C2 URL**
- Given I am an authenticated admin
- And there is a draft auction
- And I have entered a C2 URL in the C2 Proposal URL input
- When I click the Set C2 URL button
- Then that C2 URL should be recorded for that auction
- And the system should stop checking for the existence of that URL
- And any existing jobs are canceled

**Comment by harrisj** [comment]
I have started work on this, but it looks like we will need to modify this a little. Currently there are two different C2 statuses that default pcard auctions go through when the request is made

1. When the admin clicks Request Approval, this fires off a job to create the C2 proposal and sets the `c2_status` to `sent`
2. The background job then posts a new proposal within C2, saves the proposal URL in the auction record and sets its status to `pending_approval`
3. When the C2 background checker notices that the proposal is approved, it then set the auction to be `budget_approved`.

If the C2 API is down, then both steps 2 & 3 will fail. This means, I will need to add this input option to screens for both the `sent` and `pending_approval` statuses.

1. Do you have some standard text you would prefer to preface the box? Do we want to do it this way or should we give them an option to select the C2 status of the auction on the edit form (there is a field for editing the C2 URL in there)

**Comment by harrisj** [comment]
Oh, I see, this should just let people add the C2 URL for the auction
