### ISSUE TITLE
On login page, SAM.gov should be a link

### ISSUE THREAD

**Issue by khandelwal** [18F/micropurchase#137]
If you're redirecting folks to sam.gov:

"Before participating in this marketplace, you’ll first need to register your company with SAM.gov to receive a DUNS number, and have a GitHub account."

make that SAM.gov piece a link so that someone can easily click on that to go register.

**Comment by awfrancisco** [comment]
Fixed in #140

**Comment by allalala** [comment]
Closing on account of completion.
