### ISSUE TITLE
Admin can mark C2 request as approved

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1370]
As an admin, I want to be able to manually approve a C2 request if the C2 integration fails.
- [ ] **Scenario: Admin sees "Approve C2 Request" button for auction awaiting C2 approval**
- Given I am an authenticated admin
- And there is a draft auction
- And that auction has a C2 request
- And that auction is awaiting approval
- When I go to the auction show page (https://micropurchase.18f.gov/admin/auctions/[id])
- Then I should see in the auction status box a button labeled "Approve C2 Request"
- [ ] **Scenario: Admin manually approves C2 Request**
- Given I am an authenticated admin
- And there is a draft auction
- And that auction has a C2 request
- And that auction is awaiting approval
- And I am on the auction show page (https://micropurchase.18f.gov/admin/auctions/[id])
- When I click on the "Approve C2 Request" in the auction status box
- Then the C2 request for that auction should be approved
- And the system should stop checking for approval of that C2 request
- And all existing jobs should be canceled

**Comment by harrisj** [comment]
I'm not really sure how I missed this one
