### ISSUE TITLE
On login page, make small print smaller

### ISSUE THREAD

**Issue by khandelwal** [18F/micropurchase#138]
There's 'small print' on the login page. Can we visually separate that, so that it's clear it's not really 'part' of the login page? Or literally make that small print? 

<img width="1021" alt="screen shot 2015-12-18 at 2 43 55 pm" src="https://cloud.githubusercontent.com/assets/636752/11905707/e52da1f6-a595-11e5-860d-586e00be69f8.png">

**Comment by allalala** [comment]
Thank you. Sending this over to @nickbristow and @ddotrollins

**Comment by nickbristow** [comment]
@allalala was this mention meant for @brethauer ?

**Comment by allalala** [comment]
Yup. Sorry about that. Definitely meant to loop in @brethauer

**Comment by jessieay** [comment]
We are changing the login page design /flow. in a different set of stories. closing!
