### ISSUE TITLE
User feedback sessions

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1384]
Questions to ask:
1. How was the bidding experience? 
2. Why did you not deliver (Dan Siddoway)
3. When you look at the insights what kind of information do you find useful?
4. What do want to know about the micropurchase platform that you don't already know? For what purpose?
5. What do you wish the platform did?

**Comment by mtorres253** [comment]
We still have one vendor interview left. @jehlers emailed the vendor yesterday. Waiting for response

**Comment by mtorres253** [comment]
Hi @jehlers are we done with this? If so would you move it to the done column and post a link to the research doc in this issue?

**Comment by jehlers** [comment]
Yep yep! Here are the notes: https://docs.google.com/document/d/1x617-Cpoenf62hZYpUwYM71fzt8bPdWOZzKcs6u67ds/edit#heading=h.otb2xkwr104t
