### ISSUE TITLE
Admin view - Needs Attention - "Date Delivered" field contains wrong data

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1385]
To duplicate (until 10/28/16)

Go to https://micropurchase.18f.gov/admin/auctions/needs_attention

Expected behavior: In the "Needs Evaluation" section, The "Date Delivered" column should contain the date the auction was marked as done by the vendor. 

Actual behavior: The field seems to show days to delivery date (see attached)

<img width="1078" alt="screen shot 2016-10-26 at 8 57 36 am" src="https://cloud.githubusercontent.com/assets/100149/19733986/b45a104e-9b5a-11e6-8452-02f89e0fabda.png">

**Comment by harrisj** [comment]
It doesn't look like we record when the vendor actually marked an auction as delivered

**Comment by mtorres253** [comment]
@harrisj Maybe we should start to implement the solution we were talking about (paperclip?). We keep wanting to see dates and then they are not recorded :(  For now, can we just change to the delivery deadline? At least that would give me a sense of which one takes priority for evaluation

**Comment by harrisj** [comment]
I will change to delivery_deadline
