### ISSUE TITLE
Engage with the content strategy team to help

### ISSUE THREAD

**Issue by khandelwal** [18F/micropurchase#139]
Looking at the current pages, it might be a good idea to engage with the content strategy team to help design the content - especially around introducing the project and it's goals.

**Comment by allalala** [comment]
@awfrancisco very interested in engaging with your team on this

**Comment by mtorres253** [comment]
hi @alla can you update this story when you have a moment? Is there anything that we still need?

**Comment by mtorres253** [comment]
Content was reviewed and revised since this story was created
