### ISSUE TITLE
Admin view - Auction show - Auction accepted - Messaging broken

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1395]
I recently accepted an auction by clicking the "Accept" button and the messaging seems broken

To duplicate:
Go to https://micropurchase.18f.gov/admin/auctions/44

Expected behavior:
You see the appropriate message https://github.com/18F/micropurchase/issues/1016

Actual behavior:
You see an error

<img width="613" alt="screen shot 2016-10-27 at 11 45 49 am" src="https://cloud.githubusercontent.com/assets/100149/19780976/2b1c9742-9c3c-11e6-85a8-80af6485c313.png">

**Comment by harrisj** [comment]
Ooof, let me look into that now
