### ISSUE TITLE
As a admin, I want to approve bidders so that they can start bidding on auctions/issues

### ISSUE THREAD

**Issue by baccigalupi** [18F/micropurchase#14]
Given I am a logged in admin
And I visit the adming/bidders page
I should see a list of bidders with information
And each bidder should have an indication of whether they have been approved
When I click to approve a bidder
Then I should see that they have been approved
When I click to remove approval from the bidder
Then I should see that they are no longer approved

**Comment by adelevie** [comment]
per @vzvenyach, verification is not a requirement to make a bid for launch. We will still be verifying bidders as they register and as they win auctions.

**Comment by blacktm** [comment]
Right, this will be a passive verification for now, not a dedicated approval by admins.
