### ISSUE TITLE
User research - internal customers

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1410]
**Acceptance criteria**

Interview
- Steven Reilly
- Laura G

Script:
- Current pain points
- Goals
- Wishes
- Anything else?

**Comment by jehlers** [comment]
@mtorres253 Just created some discussion guidelines for both these discussions and the ones in #1384. Let me know what you think! https://docs.google.com/document/d/1ntaJFep8Y-Liz5R3zpqwHMVeLDgxN-ESe__iTyuCqyY/edit#

**Comment by mtorres253** [comment]
Hi @jehlers are we done with this? If so would you move it to the done column and post a link to the research doc in this issue?

**Comment by jehlers** [comment]
Yep yep! Here are the notes: https://docs.google.com/document/d/1CafoWgKisLbRKo2A2swY2OprnR4dCJLorgxOTeXd34o/edit
