### ISSUE TITLE
Organize data for insights page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1416]
We want to just take the existing numbers and organize/prioritize them. We just want to take a stab at this (including what we have already organized here:

https://docs.google.com/a/gsa.gov/document/d/1QA8r1__aKcH_hJ0fUO_R2oIIOpAHgGpdx4sft6lDjis/edit?usp=sharing

Acceptance criteria
1. Document with new list of insights ready for design/visuals.

**Comment by jehlers** [comment]
Started a mural to visually organize the stats and hopefully support a voting exercise: http://mur.al/v88JBMP7

**Comment by jehlers** [comment]
Here's a doc with the current organization: https://docs.google.com/document/d/1XXeFsFJuLxZMruoaATMzWen0vjj0dOVSIytTtqwY77s/edit Next step, designs!
