### ISSUE TITLE
Customer research

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1425]
We want in these interviews to get a sense of what is the perceived value of the micro-purchase platform and how customers want to use it to achieve their goals. We might also want to ask them about metrics on the insights page

Lisa Nelson (Open opps)

Kelley Bailey (Calc) 

Bret Mogilefsky (Cloud.gov)

**Comment by mtorres253** [comment]
Hi @jehlers are we done with this? If so would you move it to the done column and post a link to the research doc in this issue?

**Comment by jehlers** [comment]
Yes! Here are the notes: https://docs.google.com/document/d/13UUZkA-Nj4MQhAEu1gZ1bBQZ1xojmYnRgfqvQ_qzFbA/edit
