### ISSUE TITLE
Handling of operations work for Chandika / Raktabija

### ISSUE THREAD

**Issue by alain-hoang** [18F/micropurchase#1508]
Infrastructure makes use of a tool known as [Chandika  / Raktibja](https://github.com/18F/chandika) for keeping tabs on cloud instance allocations.  The tool is currently written in PHP and the main author is no longer with 18F.  Am looking to see if it is viable to handle operations support of this via the micropurchases platform:   

Tasks could include:
 - schedule cadence of re-deploy of updated buildpacks
 - validate that known CVEs are being checked, either in the core PHP code or in any libraries or dependencies the PHP is reliant upon
 - Update of any relevant documentation

**Comment by mtorres253** [comment]
Hi Alain, this might be something we can do. Can you fill out an issue in this repo https://github.com/18F/micropurchase-auctions? there is template that guides you through all the questions we need answered so that we can give you an answer.

**Comment by alain-hoang** [comment]
Thanks Michael, I've moved this issue to micropurchase-auctions.  I'll close this one out in favor of the one there
