### ISSUE TITLE
As a site visitor, I should be able to see the detail view on any issue

### ISSUE THREAD

**Issue by baccigalupi** [18F/micropurchase#16]
Given I am not signed in
Then I should be able to click on the detail view for any issue
And I should see details about the current bid

**Comment by baccigalupi** [comment]
This is done in the user flow sense. When you click on the bid link on the home page, you are brought to the detail view. @blacktm do we want another link that does not imply that you need to bid to see more details on the auction?

**Comment by blacktm** [comment]
@baccigalupi I don't think so. The same information will be on the bid page (for now at least), so this is good to go.

**Comment by blacktm** [comment]
Thinking more about this, I think having a "show" route for auctions/issues makes a lot of sense for unauthenticated users, so folks can share URLs on GitHub and elsewhere.
