### ISSUE TITLE
On mobile, site is scaling vs. responding

### ISSUE THREAD

**Issue by ddotrollins** [18F/micropurchase#174]
@vzvenyach When the site is opened on a desktop browser, the site properly responds as you resize the browser window. When loaded on a mobile device (i.e. iPhone), the site scales to a smaller viewport versus responding to the mobile convention. This may be a CSS tweak since the issue arrived during that process.

See this for the iPhone view: 
![mobileview_iphone](https://cloud.githubusercontent.com/assets/9273855/12026466/cdaf226c-ad87-11e5-91d4-14167e10f697.PNG)

Desktop View (intended):
<img width="480" alt="micro-purchase desktop view" src="https://cloud.githubusercontent.com/assets/9273855/12026502/41d79b60-ad88-11e5-9738-86ff90b2879e.png">

**Comment by harrisj** [comment]
Addressed in pull request #189

**Comment by allalala** [comment]
:white_check_mark:
