### ISSUE TITLE
As a site visitor, I should be prompted to sign in when trying to bid on an issue

### ISSUE THREAD

**Issue by baccigalupi** [18F/micropurchase#18]
Given I have not signed in
And I visit the detail page of an issue
Then I should see a button prompting me to sign in to bid
And when I click it, I should be redirected to github to authenticate
And when I return I should be prompted for my duns and sam id
And when I complete that information, I will finally be redirected to the detail page containing a bid form

**Comment by baccigalupi** [comment]
I think this is done. We may need to wait until the real data views are done to confirm

**Comment by blacktm** [comment]
Also, if user has authenticated via GitHub, but not completed their profile, they should be redirected to do so.

![screen shot 2015-10-22 at 5 32 01 pm](https://cloud.githubusercontent.com/assets/887429/10678886/11bd93d2-78e3-11e5-80f3-c5cddd3dc35b.png)

**Comment by blacktm** [comment]
Completed in #68
