### ISSUE TITLE
As an admin, I want to create new issue/auctions

### ISSUE THREAD

**Issue by baccigalupi** [18F/micropurchase#20]
Given I am logged in as an admin
And I go to the admin/issues/new page
Then I should see a form for entering new auctions into the app
When I complete the form
Then I will have created a new auction with the details provided

Given I am a non-admin signed in user
When I try to go to the new issues page
Then I will be redirected to home

**Comment by blacktm** [comment]
@adelevie and I talked about this, and admins should probably be able to do CRUD operation on any model.
