### ISSUE TITLE
Check for SAM registration at time of site registration

### ISSUE THREAD

**Issue by vzvenyach** [18F/micropurchase#213]
Right now the SAM registration check is done as part of a batch check, but it's confusing for new site registrants who *are* in SAM when they get the error message that they're not in SAM.

cc: @adelevie @harrisj

**Comment by vzvenyach** [comment]
Just as a side note, you may want to add a `sleep 1` to this until we get the SAM API rate limiting increased. It'll slow down registration, but it'll help avoid false negatives.

**Comment by adelevie** [comment]
As discussed earlier, we're passing on this in favor of a minor change to the copy text. Until we can get some generous rate limits from SAM.gov, we will not make requests to SAM.gov user-driven.
