### ISSUE TITLE
Add auction start time

### ISSUE THREAD

**Issue by adelevie** [18F/micropurchase#217]
See https://micropurchase.18f.gov/auctions/7.

**Comment by milafrerichs** [comment]
So I started working on this issue and have a couple of questions/remarks:
(Screenshots are from my current branch using the seeds)

1. I assume you want to show the time left in human words when a auction is not yet started:
<img width="784" alt="bildschirmfoto 2016-01-14 um 12 04 53" src="https://cloud.githubusercontent.com/assets/688980/12322854/0f3148aa-bab7-11e5-829b-5f46ecf69e15.png">

2. I assume you don't want to display the start time once a auction is finished:
<img width="769" alt="bildschirmfoto 2016-01-14 um 12 06 13" src="https://cloud.githubusercontent.com/assets/688980/12322885/471e4a60-bab7-11e5-833a-cb5ddca5c0a9.png">

3. I assume you want to display the start time below the end time when a bid is currently running:
<img width="789" alt="bildschirmfoto 2016-01-14 um 12 07 09" src="https://cloud.githubusercontent.com/assets/688980/12322901/6db1f6e0-bab7-11e5-9060-332bc67c3175.png">

4. I assume you want to display the start time below the end time on the detail page:
<img width="256" alt="bildschirmfoto 2016-01-14 um 12 08 53" src="https://cloud.githubusercontent.com/assets/688980/12322934/ae953f6e-bab7-11e5-86a2-212efe5de1f0.png">


Could you please provide guidance on the wording: e.g. `Bid start time`

### Styling

For which browsers should the code be optimized? Do you still support IE6/7?
I assume you want to vertical align the text in the center?
<img width="787" alt="bildschirmfoto 2016-01-14 um 12 12 27" src="https://cloud.githubusercontent.com/assets/688980/12323064/c27c9788-bab8-11e5-965b-f6fec044b723.png">
