### ISSUE TITLE
As a bidder, I want a clear indication of whether my bid on an issue is the winning bid

### ISSUE THREAD

**Issue by baccigalupi** [18F/micropurchase#22]
Given I am an authenticated and approved bidder
And I have posted a bid
And I am the lowest bid
Then I want to see on the issue detail page a clear indication that I am the current winner

**Comment by blacktm** [comment]
This also implies users should be able to see all issues they have placed bids on.

![screen shot 2015-10-22 at 5 21 49 pm](https://cloud.githubusercontent.com/assets/887429/10678648/b2c4bd34-78e1-11e5-8592-6007d7fecf8e.png)

**Comment by JoshData** [comment]
As a bidder on a particular auction, if I am not the winner, clear indication of that would be helpful as well --- because I don't remember what I bid.

**Comment by JoshData** [comment]
Just for reference, this applies to `/`, `/my-bids`, `/auctions/{id}`, and `/auctions/{id}/bids`.
