### ISSUE TITLE
Standardize on hyphenation of "micropurchase"

### ISSUE THREAD

**Issue by gboone** [18F/micropurchase#224]
The site at https://micropurchase.18f.gov/ inconsistently hyphenates the word "micropurchase." In most of the copy the word is hyphenated `micro-purchase` but in the URL, at the H1 heading, and in the `title` it is not hyphenated. In the 18F blog, and in the blog's tags, it is typically hyphenated but [in at least one instance](https://18f.gsa.gov/2016/01/07/announcing-the-18f-micro-purchase-platform/#auction-types:-iterating-on-reverse-auctions-(for-now!)) it is not. In posts about [micro-purchasing that are not about the reverse auction system](https://18f.gsa.gov/2015/08/06/communicart-tool-will-streamline-purchase-card-process/) we have used a hyphen.

It seems like hyphen is the way to go but whatever decision is made should also be added to the 18F content guide.

**Comment by rebeccawilliams** [comment]
Looks like this is being discussed in #134 as well.

**Comment by gboone** [comment]
Closing in favor of #134
