### ISSUE TITLE
$1 bid increments are initially way too small (As a user, I #ugh.)

### ISSUE THREAD

**Issue by JoshData** [18F/micropurchase#225]
When the low bid is, say, $500 or more, a $1 increment is frustrating because someone can undercut you without making a real change in the bid price. It's effectively bidding the same amount, but with precedence.

Maybe the increment should be relative to the current low bid. i.e., The next bid has to be at least 1% less than the current low bid, bottoming out at $1.

(Possibly better would be to not making this live bidding at all, and just have parties submit their lowest price. Some rules then award based on the next higher price, so there's no risk to the bidder of bidding too stupidly low.)

**Comment by adelevie** [comment]
Thanks for the feedback @JoshData. 

Would an eBay-style [auto-bid](http://pages.ebay.com/help/buy/bidding-overview.html#auto) obviate the need for this?

And absent an auto-bid feature, what increments would be useful to you?

One side effect of increasing the bid increments would be that the lowest possible bid would also increase. (e.g. $50 increments would mean that someone bidding $50 would immediately win and lock in that price).

**Comment by JoshData** [comment]
> Would an eBay-style auto-bid obviate the need for this?

Yes definitely. Although I'm not sure how live bidding in any form is better than having everyone submit a bid once... and that's it.
