### ISSUE TITLE
More precise auction closing text

### ISSUE THREAD

**Issue by harrisj** [18F/micropurchase#230]
Rather than using Rails' vague `distance_of_time_in_words` let's get more precise with this gem https://github.com/radar/dotiw

**Comment by harrisj** [comment]
Not sure this a priority actually. Would be cooler to have it count down in the browser via javascript

**Comment by adelevie** [comment]
I'm :thumbsup: on this.

**Comment by allalala** [comment]
As a vendor, I would like to know the very specific time an auction ends.
