### ISSUE TITLE
Bids Amount Display Problem

### ISSUE THREAD

**Issue by jfc3-dol** [18F/micropurchase#265]
While viewing bids on my iPhone 4s, the bid prices are overlapping the rest of the text in portrait mode at the end of a bid. Not sure if the issue exists with a smaller amount like $19.95 or will happen for amounts higher than $100 or become an even bigger problem if bids are in the thousand ( $1,234.56), tens of thousands ($12,345.67), or hundreds of thousands of dollars ($123,456.78).

My suggestion would be to place the amount under the word "Current Bid" so you have even more room. You don't need the colon ":" since it will be read by a screen reader such as JAWS as "current bid colon".

Please see the screenshot of the issue.

![18f bid amouint error](https://cloud.githubusercontent.com/assets/10423487/12655468/15d489b8-c5c7-11e5-9848-f1a0cc75170c.jpg)

**Comment by jessieay** [comment]
Thanks for creating this issue! We changing our homepage design so this should no longer be an issue. Closing.
