### ISSUE TITLE
Number of registered users is leaked/detectable

### ISSUE THREAD

**Issue by bwillard** [18F/micropurchase#266]
Using a monotonically increasing integer as a public identifier leaks potentially private information.

For instance after registering I was on a page: https://micropurchase.18f.gov/users/XXX/edit,

because the error messages are different for the pages:

https://micropurchase.18f.gov/users/<validUser>/edit and https://micropurchase.18f.gov/users/<invalidUser>/edit

it is possible to tell how many users are registered.

Given the open nature of this experiment this probably isn't a concern, but as a platform that might get used for other projects it is probably a bad practice.

**Comment by adelevie** [comment]
Hey @bwillard, thanks for bringing this to our attention. I think we will probably harmonize the error codes so as not to leak the # of users this way. Neverthless, we might end up releasing user stats/data any way as part of the API.

**Comment by allalala** [comment]
Thank you for the issue @bwillard. We always appreciate community feedback.
