### ISSUE TITLE
As a user, I want real data to populate the views.

### ISSUE THREAD

**Issue by blacktm** [18F/micropurchase#27]
None of the views use real data at the moment. We'll use ERB for this.

**Comment by adelevie** [comment]
Data on `/` is real, but data on `/auctions/1/bids/new` is still static:
<img width="1035" alt="screen shot 2015-10-22 at 3 43 51 pm" src="https://cloud.githubusercontent.com/assets/86790/10676399/d84acf20-78d3-11e5-8e81-58593a557c09.png">

**Comment by blacktm** [comment]
This is now dynamic :+1:
