### ISSUE TITLE
Ensure enough data is stored to one day POST requests to CAP

### ISSUE THREAD

**Issue by adelevie** [18F/micropurchase#274]
<img width="212" alt="screen shot 2016-02-02 at 9 11 52 am" src="https://cloud.githubusercontent.com/assets/86790/12751774/132af98a-c98d-11e5-8dec-3ec3fdc4b96d.png">

Office: hardcode to DC.
Purchase type: hardcode to software.
Product name and description: auction.title and auction.summary.
Justification: "Custom software procured via the micro-purchase platform" (???)
Link to product: auction.issue_url.
Cost per unit: auction.winning_bid.amount
Date requested: DateTime.now
Urgency: w/in a week.
Additional information: something suitable for tock (maybe comes from notes? nahhh)

**Comment by jessieay** [comment]
this is done! we did it 🏁 ✔️  -- closing!
