### ISSUE TITLE
UI cleanup TODOs for single-bid

### ISSUE THREAD

**Issue by adelevie** [18F/micropurchase#312]
<img width="732" alt="screen shot 2016-02-23 at 4 08 01 pm" src="https://cloud.githubusercontent.com/assets/86790/13266792/b96840da-da47-11e5-81e4-8dde81972867.png">

- [x] in `auctions#show`, the flash message after bid placement says "you are the current winning bidder"

<hr />

<img width="732" alt="screen shot 2016-02-23 at 4 13 39 pm" src="https://cloud.githubusercontent.com/assets/86790/13266937/6dcb47a2-da48-11e5-9d32-5d30e0c8ed05.png">

- [x] in `auctions#show`, the the flash message in a refresh after bid placement reverts to "You currently do not have the winning bid."

<hr />

<img width="237" alt="screen shot 2016-02-23 at 4 09 02 pm" src="https://cloud.githubusercontent.com/assets/86790/13266802/c806b96e-da47-11e5-86f5-03a420ef1335.png">

- [x] in `auctions#show`, the the bid box lists the current bidder and the number of bids.

<hr />
```
A Single Bid Auction is a type of reverse auction. Each bidder is only allowed to submit one bid through the entirety of the auction. Once a bid is submitted, the vendor cannot submit a second bid for the same auction. 

Like the first form of the experiment, the lowest bidder will still win each auction. In the event of a tie, the vendor who was first to submit the lowest bid amount will win.
```

- [ ] Add @allalala's copy to the `auctions#single_bid_rules` view.

**Comment by jessieay** [comment]
This is done - closing!
