### ISSUE TITLE
As a developer, I would like to see CodeClimate post commit hooks, so that I know what effect my work has on the overall code quality

### ISSUE THREAD

**Issue by baccigalupi** [18F/micropurchase#37]
Adding the commit hook needs to be done by the organization owner. Currently I have the badge setup via my own login. I would really like to get this in our commit process ... and even better I would like to see code coverage too.

http://docs.codeclimate.com/article/222-how-do-i-install-code-climates-github-service-hook
http://docs.codeclimate.com/article/219-setting-up-test-coverage

**Comment by adelevie** [comment]
I set up the Code Climate PR integration.
