### ISSUE TITLE
Storing payment URL

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#373]
Feature:
As a bidder and as an admin user, I want to make sure that the payment process goes as smoothly as possible, so there should be a way to specify a payment URL when it exists, so that payments can be sent directly to that URL, and so that the bidder and admin can be confident that payments are going to the right place.

**Comment by adelevie** [comment]
We currently have a column in the database for the URL. But we have no UI enabling a vendor to enter it.

**Comment by mtorres253** [comment]
Let's talk about this one today. I want to finish this feature so that we can start working on it.
