### ISSUE TITLE
Payment URL validation

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#374]
As a vendor, I want the system to tell me if there is a problem with my credit card URL before it gets associated with my account, so if there is something wrong with it, the system should not save my entry and should notify me of the problem

Scenario: Vendor cannot save credit card URL with invalid format
Given I am an authenticated vendor
And I have entered a value for credit card URL on my profile page
But it is not in the form of a URL (http://www.domain.com for example)
When I click "Save"
Then the URL I entered should not be saved to my account
And I should see an error message "The URL you have entered is not valid"

Note: Let's discuss what is possible in addition to this. Do we want to require https:?

**Comment by harrisj** [comment]
Can we have it just note the error on a Submit rather than when we tab out of it?
