### ISSUE TITLE
Admin publishes auction with start price of over $3500

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#391]
As an admin who has permission to publish auctions over $3500, I want some way to do this via the admin UI, so there should be some UI control that allows me to do this

Scenario: Admin with permission approves auction over $3500
Given that I am an admin user
And I permission to publish auctions over $3500
And an auction exists that has a start price over $3500
And I've selected published from the Published? dropdown
When I click the save button
And there are no other errors
Then the auction should be published
And the system should record that I published the auction

Note: the system should record who published the auction

**Comment by jessieay** [comment]
This was finished via https://github.com/18F/micropurchase/pull/510

**Comment by mtorres253** [comment]
Duplicate of #510
