### ISSUE TITLE
Auctions where bidding starts at > $3500 are sealed bid

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#394]
As an admin user who is managing auctions over $3500, at least to start, I want to have an easy way to pick a clear winner, so that I don't have to spend a lot of time managing the auction, and so that it's less likely I will pick the wrong one, so, let's start by saying that all auctions over $3500 are sealed bid auctions.

Scenario: Admin creates an auction with value over $3500
Given I am an authenticated admin user
And I have permission to create an auction over $3500
When I have filled out the form to create an auction over $3500 in value
And I save the auction
Then the auction should be saved as a sealed bid auction

Note there may be some additional work here.

**Comment by harrisj** [comment]
I'm wondering if we should change the name of `single-bid` to `sealed-bid` while it's easier

**Comment by mtorres253** [comment]
Good point. I think this would be a good time to do that. It's standard auction language and as long as what we're doing matches that, then we should switch sooner rather than later.

**Comment by mtorres253** [comment]
Closed this issue as we decided we don't need to restrict these types of auctions to sealed bid because we will be able to identify businesses as small businesses.
