### ISSUE TITLE
Asset management

### ISSUE THREAD

**Issue by gemfarmer** [18F/micropurchase#401]
The asset set up is a bit funky. A few issues:

* vendor assets for js and css should be in `vendor/assets` when possible. This list includes:
  * /app/assets/javascripts/winners/d3.min.js
  * /app/assets/javascripts/winners/underscore.js
  * /app/assets/javascripts/c3.js
  * /app/assets/javascripts/jquery-accessibleMegaMenu.js
  * /app/assets/stylesheets/source/c3.css
  * /app/assets/stylesheets/us-web-design-standards should be kept (for access to variables)
* Not all assets are being loaded in production
<img width="663" alt="screen shot 2016-04-12 at 12 21 59 pm" src="https://cloud.githubusercontent.com/assets/4803473/14473377/50ccc9fa-00bd-11e6-91c5-96ba6e4d8e7a.png">

**Comment by harrisj** [comment]
I moved some more of these over as part of #404
