### ISSUE TITLE
Cross walk existing winners with PDF data 

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#403]
So that we can have an idea of whether we can scrape the Sam certification PDF to see if a business is a small business, let's see if this can be derived for existing winners

Example Sam.gov response
https://api.data.gov/sam/v1/registrations/1459697830000?api_key=vqKxyOIW6XLkedDF3zchd03CJkgTYPwsCJzo5fzd

**Comment by adelevie** [comment]
Is there a link to the PDF?

**Comment by vzvenyach** [comment]
After spending a little time researching this issue, I found that, in *fact* we can programmatically determine whether a business is a small business using V4 of the SAM API (samwise currently uses v1, so we may want to see whether this breaks anything, and if it does, we should update it anyway). 

For example, take a look at https://api.data.gov/sam/v4/registrations/0800374780000?api_key=DEMO_KEY. If you search for the object where `id="FAR 52.219-1"` in `sam_data .registration.certifications.farResponses`, there is a small business indicator for a particular NAICS code.

**Comment by vzvenyach** [comment]
PR that would allow for programmatic lookup of whether a vendor is a small business is here: https://github.com/18F/samwise/pull/23

**Comment by jessieay** [comment]
open questions:

> how do we store this info?

> do we only allow small bizs to bid?

**Comment by jessieay** [comment]
@vzvenyach looks like you already did the research for this issue so we can consider it done. Going to review your samwise PR now 🌈
