### ISSUE TITLE
If DUNS number is not found in Sam.gov, vendor sees error

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#409]
As a registered vendor, I want to know if there is a problem with any of my profile data so that I can correct it, so the system should tell me

Scenario: System cannot find DUNS number in Sam.gov
Given that I am a registered vendor
And the system has not been able to find my DUNS number in the Sam.gov
When I go to my profile page
I should see an indication that my DUNS number has not been found "Your DUNS number was not found in Sam.gov. Please enter a valid DUNS number to complete your profile. Check https://www.sam.gov/sam/helpPage/SAM_Reg_Status_Help_Page.html to make sure your DUNS number is correct. If you need any help email us at micropurchase@gsa.gov"

Note: Let's discuss to see if we can make this more specific in terms of messaging

**Comment by jessieay** [comment]
PR for this here: https://github.com/18F/micropurchase/pull/441
