### ISSUE TITLE
If DUNS number is found in Sam.gov, profile page shows that it is valid

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#410]
As a registered vendor, I want to know if my profile data is valid, so if the system can show me this, it should

Scenario: System shows vendor that DUNS number has been verified in Sam.gov
Given I am a registered vendor
And the system has verified my DUNS number in Sam.gov
When I go to my profile page
Then I should see an indication that my DUNS number has been verified

Note: Let's talk about details like messaging. Let's start with this message in a green alert box "Your DUNS number has been verified in Sam.gov"  We can check with @andrewmaier later to maybe get some kind of nifty icon?

**Comment by harrisj** [comment]
Can we clarify what it means for the system to have validated the DUNS? Does this mean checking that the DUNS is registered with SAM.gov?

**Comment by jessieay** [comment]
We already have the logic for this in the backend, just need design/copy for surfacing "valid DUNS number" status to user

**Comment by jessieay** [comment]
https://github.com/18F/micropurchase/pull/444

**Comment by harrisj** [comment]
Are we good to close this issue?

**Comment by jessieay** [comment]
this will closed via #444 - Michael says we should move to "completed" once that is out of QA...
