### ISSUE TITLE
Chart rendering on staging

### ISSUE THREAD

**Issue by gemfarmer** [18F/micropurchase#412]
On [staging](https://micropurchase-staging.18f.gov/auctions/winners) there is a soft bug that looks like this in the console. It is likely caused by the circles being defined in the "Auctions by bid" chart not having a valid (likely undefined) bid amount.
<img width="508" alt="screen shot 2016-04-12 at 3 03 36 pm" src="https://cloud.githubusercontent.com/assets/4803473/14473897/f4832d4e-00bf-11e6-9685-805528e036e9.png">

**Comment by harrisj** [comment]
Closing since this seems to be fixed now.
