### ISSUE TITLE
Payment request is submitted when auction is accepted

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#417]
As an admin user, I want my p-card payments to be automated, so that I don't have to worry about making a mistake or forgetting to pay a vendor who wins an auction

Scenario: Payment request to CAP is made automatically when auction is accepted
Given I am a registered admin user
And there is an auction with a winner
When I accept the auction on the auction edit page (select "Accepted" from result dropdown)
Then a payment request should be made via the Communicart (CAP) API to the correct card
And if there are no errors 
Then I should see a success message (Congratulations! The payment request to [vendor] for [auction name] has been made.]
And I should be taken to [whatever the current behavior is]
And when I login to communicart, i can see that the payment request has been made

Notes: Start with staging, so that we can make sure the loop is working, then deploy to production when C2 deploys their API to production

**Comment by gemfarmer** [comment]
@mtorres253, @jessieay has been working on Communicart, so might be helpful with this once she is onboarded

**Comment by adelevie** [comment]
Thinking/writing out loud:

To implement this, I believe we want to start a(n async) API call to CAP whenever the `status` attribute on `Auction` is saved to `'accepted'.` Currently, Auctions are updated using the `UpdateAuction` class. Do we want to make something in this class that checks for this specific change to the model and act accordingly? Is there a clean way to create an observer instead?

**Comment by jessieay** [comment]
To repeat comment from slack: could use `success` hook that DJ gives us https://github.com/collectiveidea/delayed_job#hooks
