### ISSUE TITLE
Auto-email to losing bidders

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#421]
As a vendor, I want to receive accurate notifications when significant events occur for a given auction, so there should be a way for me to receive auto-emails

Scenario: Losing bidders get email notification that they lost the auction
Given I am an authorized vendor
And there is an auction (multi-bid or sealed-bid)
And I have made a bid on an auction
And there are other bids that are lower than mine
When the auction ends
Then should receive an email message telling me that I was outbid
And the email message should go to the email address in the vendor profile
And the email message Subject should be “18f Micropurchase Auction Status”
The from address should be “admin@micropurchase.gov”
And the email message body should be 
“Dear [Vendor Name]”

"This email is to inform you that your bid for [auction name] was not the winning bid. For more information please see the auction details here [link to auction]'

"Thank you for your participation and we look forward to working with you in the future."

"Sincerely,"

"The 18f Micropurchase team"

Notes: We need to craft language. Any good writers in the group?

**Comment by jessieay** [comment]
everyone here cool w mandrill for smtp server? figure v1 of email will be text-only.

**Comment by harrisj** [comment]
I'm on board with using Mandrill and being text-only to start

**Comment by mtorres253** [comment]
yep, text only to start. We can add more functionality as indicated

**Comment by jessieay** [comment]
since name is not currently a required field, I vote we do not include the `Dear` `line in the proposed text

**Comment by jessieay** [comment]
PR https://github.com/18F/micropurchase/pull/463
