### ISSUE TITLE
User research for Micropurchase

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#423]
This is a placeholder story for conducting user interviews, and synthesizing them. The research plan is here: https://docs.google.com/document/d/1zhYGaLJneidQoGMOZFUwCLqd9xw_XqkdgE5RMbLDKSQ/edit

**Comment by mtorres253** [comment]
Per planning today, we're shooting for having all the interviews and synthesis done during this sprint.

**Comment by mtorres253** [comment]
@andrewmaier have you started this yet? If so would you move to "current"?

**Comment by mtorres253** [comment]
Hi @andrewmaier can you add an update to this story? Have all interviews been completed? Are personas done? If not, what are any blockers? Projected timeline?

**Comment by andrewmaier** [comment]
https://docs.google.com/document/d/17VF_qITKp8kAGcpmXzlTOgINiF7fAda53vvt-ucMTG8/edit
