### ISSUE TITLE
End date is not displaying correctly on Admin auctions index page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#435]
To duplicate

Login to staging
Navigate to https://micropurchase-staging.18f.gov/admin/auctions
Note that the auction "Optimized Neutral Groupware" has an end date/time as 4/18/16 09:40:40 PM
Click on the edit link for that option https://micropurchase-staging.18f.gov/admin/auctions/2/edit

Expected behavior:
The end date/time should also be 4/18/16 09:40:40

Actual behavior:
The end date/time is 2016-04-19 01:40:40 +0000

**Comment by jessieay** [comment]
just spoke w Michael about this

- looks like database time saves in UTC but we are also showing EST in various places
- step 1 can be to clarify time zone on each timestamp
- step 2 can be to either standardize one one (EST or UTC) OR we could have auctions expire on a date instead and then just all auctions close at the same time each day

**Comment by mtorres253** [comment]
Should this be rephrased as a feature? Is there a reason why people can select a time (rather than just a day)? My instinct is that we can just have all auctions start and end at given times and just let users change the dates. We can just make those times explicit so everyone knows when the auction begins/ends. Could also be less confusing to vendors.

**Comment by harrisj** [comment]
I don't know about if people should be allowed to pick a time or if we should just standardize on one generally like 5pm ET or such. But I wanted to know that we do have an `Presenter::DcTime` model that is used for wrapping date times and displaying them in DC's timezone (which is the only accepted and valid timezone on the planet of course). So, in the short run, we should check to see if there are times that aren't being properly wrapped. In the long term, should we consider some sort of timezone localization for users?

**Comment by mtorres253** [comment]
Until I have more information, not comfortable making much of a product decision here. So, let's just show the timezones so that people don't think this is a bug.

**Comment by harrisj** [comment]
I decided to just add a label in the admin indicating the times are relative to UTC for now (we should probably consider a better datetime picker, but I didn't want to do that without a story). But I do have a question...

We currently have relative times on the auctions index page ("Auction ending about 24 hours from now") but on the auction detail page, we show the ending time in the UTC timezone. This is correct, but do we want to show that in the Eastern Timezone instead, since we have this `Presenter::DcTime` and methods that call it defined already?

**Comment by mtorres253** [comment]
@harrisj Yes, that is an issue. If we are going to implement features like that, we should probably show it in the users timezone. So, this is a bigger issue. I'm thinking of the dashboard (winner's page) as well. We should come up with some reasonable iteration. Will talk about it in grooming tomorrow

**Comment by harrisj** [comment]
I think we should close this in favor of #503

**Comment by mtorres253** [comment]
Agreed.
