### ISSUE TITLE
Pull in email address from github oauth?

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#450]
As a user who is signing up for a micropurchase account through github, I want to have my profile information populated for me if possible, so if there is a way to get my email address from github, the system should do that.

Scenario: I sign up for a micropurchase account
Given I am a new micropurchase user
And I have an email address specified in github
When I signup via github
Then my email address should be assigned to my profile
And when I view my profile page I should see my email address pre-populated in the email address field

Scenario: I login to micropurchase using my github account
Given I am a micropurchase user (admin or vendor)
And I have an email address specified in github
And I do not have an email address specified in my micropurchase profile
When I signin via github
Then my email address should be assigned to my profile
And when I view my profile page I should see my email address pre-populated in the email address field

Omniauth requires "email" scope in order to pull email directly from github.

Currently, we do not request this scope

Is there a reason why we do not request this already?

https://github.com/intridea/omniauth-github

cc @adelevie @harrisj

**Comment by jessieay** [comment]
from Slack:

Yeah, let’s request the email scope. Can we also get their their github login?

[5:02] 
I think we try to always request minimal info

Jessie Young (SF, she/her) [5:03 PM] 
what you mean login?

[5:03] 
these are available scopes https://developer.github.com/v3/oauth/#scopes

[5:03] 
I think email is a pretty good minimum

[5:03] 
it’s just read access

**Comment by jessieay** [comment]
should look into storing github username, too. currently we do this as part of a separate call to github

**Comment by jessieay** [comment]
Pretty sure we can pull both in during oauth process 

see `create_with_omniauth` method https://www.natashatherobot.com/rails-omniauth-github-tutorial/

**Comment by mtorres253** [comment]
If this can help with the email story, let's do this now. I can also tweak the acceptance criteria if we can't do it exactly as described

**Comment by jessieay** [comment]
PR for this here: https://github.com/18F/micropurchase/pull/460
