### ISSUE TITLE
Add auction_type to REST API responses

### ISSUE THREAD

**Issue by gemfarmer** [18F/micropurchase#455]
It would be useful to know if an auction is multi-bid or single-bid solely from the `/auctions` endpoint.

**Comment by gemfarmer** [comment]
#### User stories:

_As a front end developer_ on this project I want to be able to know whether auctions are single or multi bid in order to differentiate them on the [previous winners dashboard](micropurchase.18f.gov/auctions/winners/).

_As someone interested in collecting data_ about the micropurchase platform, I want to be able to know whether auctions are single or multi bid in order to better understand the micropurchase platform without hitting multiple API endpoints.

Why this is useful for the dashboard
- *Categorically different*: Our current visualizations lump distinct auction types together, which is misleading, and less informative than it could be

**Comment by vzvenyach** [comment]
Wanted to 👍 this issue. As it turns out, I had the exact question about whether different auction types affected things...

**Comment by harrisj** [comment]
Do we want to try renaming the auction types to something besides single-bid and multi-bid while we have a chance?

**Comment by jessieay** [comment]
this seems easily achievable -- just add `type` to `AuctionSerializer`
