### ISSUE TITLE
Use prebuilt admin interface

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#471]
We have several admin-related stories in the backlog. Right now, we are rolling our own admin interface. We might want to consider using something pre-built.

Rails admin: https://github.com/sferik/rails_admin

Active admin: http://activeadmin.info/

Administrate: https://github.com/thoughtbot/administrate

Any preferences? I have most experience with Rails Admin. C2 uses Active Admin. I've been wanting to try administrate.

Thoughts?

**Comment by gemfarmer** [comment]
@jessieay In what ways would the pre-built admin constrain us? Generally in favor, just want to make sure there isn't something unusual-but-necessary that we are doing that would make this a bad move.

**Comment by jessieay** [comment]
There are definitely downsides to pre built

Via Alan talking about why Kane was anti pre built:

> the context she gave was her experience rescuing apps from bad tech debt/organizational debt. And she said the admin panel gems were some of the most toxic and difficult to refactor/get rid of/customize.

Perhaps we should stick with custom. My general experience with admin interfaces is that they do eventually cause pain and at that time it is best to move away. But before then, using them gives you a lot for free!!

**Comment by jessieay** [comment]
We decided against this. Closing.
