### ISSUE TITLE
As a bidder, I want to be able to make a single bid

### ISSUE THREAD

**Issue by adelevie** [18F/micropurchase#49]
Given I am an authenticated
I should be allowed to enter a bid

**Comment by blacktm** [comment]
Also, the bid amount should be validated (whole number ≤$3,500 or less than current bid).

![screen shot 2015-10-22 at 5 25 26 pm](https://cloud.githubusercontent.com/assets/887429/10678781/6a0cb94c-78e2-11e5-8715-29a356b42b4e.png)

**Comment by blacktm** [comment]
This works :+1:
