### ISSUE TITLE
On demand report containing sam.gov data

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#495]

**Comment by mtorres253** [comment]
As an admin user, I want to be able to send required reports without having to manually find data, so if Sam.gov has the data then I should be able to easily get it from the system.

Scenario: I get a .csv file containing system auction data
Given I am an authenticated admin user
And there are auctions in the system with start prices over $3500
And those auctions have ended and there was a winner
And when I click on the link to generate a .csv report
Then the file should be generated
And the file should contain the following data from Sam.gov for the winning vendor

```csv
13GG Vendor Name, [Sam.gov Vendor Name]
13JJ Vendor Address Line 1, [Sam.gov Address Line 1]
13KK Vendor Address Line 2, [Sam.gov Address Line 2]
13LL Vendor Address Line 3, [Sam.gov Address Line 3]
13MM Vendor Address City, [Sam.gov City]
13NN Vendor Address State, [Sam.gov State]
13PP Vendor Zip Code, [Sam.gov Zip code]
13QQ Vendor Country Code, [Sam.gov Country Code]
13RR Vendor Phone Number, [Sam.gov Phone Number]
13SS Vendor Fax Number, [Sam.gov Fax Number]
```

**Comment by jessieay** [comment]
@mtorres253 suggested csv headers for these fields? should we just use the names in the text blob above?

**Comment by mtorres253** [comment]
The headers can be "FPDS Field", "Value". Does that work?

**Comment by mtorres253** [comment]
Based on today's convo, we're sticking with standard .csv format (column header, value)
