### ISSUE TITLE
Messaging to vendors about auctions with start price over $3500

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#496]
As a vendor that is not a small business, I want to know when auctions are not available for me to bid on, so the system should tell me that. 

Scenario: A vendor sees small business only auctions on the auction feed
Given I am a vendor
And there are auctions that are only available for small businesses
When I view the auction homepage (https://micropurchase.18f.gov/)
Then the previews of those auctions should show that they are only available for small businesses

Note: We can discuss this but maybe we should just have a tag that shows "Small business only"

Scenario: A vendor sees small business only auctions on the auction view page
Given I am a vendor
And I am NOT a small business
And there is an auction that is only available for small businesses
When I view the view page for that auction (https://micropurchase.18f.gov/auctions/[number])
Then I should not see the bid button
And instead I should see this message "This auction is only available for small businesses."

**Comment by adelevie** [comment]
@jessieay were you working on this? I moved this into the "current" column a few days ago, but forgot to assign myself.

**Comment by jessieay** [comment]
@adelevie nope, all you friend 🏀

**Comment by adelevie** [comment]
🎷
