### ISSUE TITLE
Vendors are marked as small businesses

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#499]
As an admin user, I want to know whether a vendor is a small business because some auctions will only be available to small businesses, so I should see some indication of that.

Scenario: User is in Sam.gov and is a small business
Given that I am an admin user
And there are users who are in Sam.gov that are small businesses
When I view the users page (https://micropurchase.18f.gov/admin/users)
Then I should see a column labeled "Small Business"
And in that column I should see a value of "Yes" for that user

Scenario: User is in Sam.gov and is not a small business
Given that I am an admin user
And there are users who are in Sam.gov that are not small businesses
When I view the users page (https://micropurchase.18f.gov/admin/users)
Then I should see a column labeled "Small Business"
And in that column I should see a value of "No" for that user

Scenario: User is not in Sam.gov 
Given that I am an admin user
And there are users who are not in Sam.gov
When I view the users page (https://micropurchase.18f.gov/admin/users)
Then I should see a column labeled "Small Business"
And in that column I should see a value of "N/A" for that user

Note: This will require some kind of check in Sam.gov for members who have a DUNS number and who are in Sam.gov. We talked about doing this every day?

Also this: 18F/samwise#23 - bake in a status check so that we get only small businesses who are active.

**Comment by harrisj** [comment]
Shouldn't this be closed?

**Comment by jessieay** [comment]
this looks like it is finished. closing
