### ISSUE TITLE
Vendor sees auction start/end times and delivery time in ET when viewing new auction details

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#501]
As a vendor, before an auction goes live, I want to be able to see auction details containing the start and end date of the bidding as well as the delivery date, so that if I am interested in an auction, I can plan to bid on it.

Scenario: Vendor views auction details before the auction is live
Given I am an authenticated vendor
And there is an auction where bidding has not yet started
When I view the details page of an auction (https://micropurchase.18f.gov/auctions/[number]
Then I should see when bidding starts and ends in ET
And I should see the delivery deadline in ET

**Comment by harrisj** [comment]
Should I make these separate features (do you want a whole story for them) or should I add these as assertions to our existing cucumber stories for viewing the auction details?

**Comment by harrisj** [comment]
For reference, here are some stories that look at auctions already:

* https://github.com/18F/micropurchase/blob/develop/features/auctions.feature
* https://github.com/18F/micropurchase/blob/develop/features/bidding.feature

We could consider if these should be constructed better and if I should add some steps to them. Or I could add new features too.

**Comment by harrisj** [comment]
Also, do we have a mockup for showing the delivery deadline on the page? Or am I just to do that?

**Comment by harrisj** [comment]
Closing since this was merged
