### ISSUE TITLE
Synch DUNS messaging on homepage with profile page messaging

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#507]
As an vendor, I want to see consistent status messages, if I see them at all, So, if the system is showing me status messages  profile page and the homepage for the same thing, they should be consistent. 

Scenario: Registered vendor goes to homepage, but has no DUNS number 
Given I am a vendor
And I have registered (signed up with GitHub)
And I have not yet entered my DUNS number
When I go to the homepage (https://micropurchase.18f.gov/)
Then I should see the following message 
"In order to bid, you must supply a valid DUNS number. Please update your profile" (your profile links to the vendor's profile page)

Scenario: Registered vendor goes to homepage, and DUNS number is being verified
Given I am a vendor
And I have registered (signed up with GitHub)
And I have saved a DUNS number to my profile
And the system is still verifying my DUNS number
When I go to the homepage (https://micropurchase.18f.gov/)
I should see the following message:
"Your profile is pending while your DUNS number is being validated. This typically takes less than one hour"

Scenario: Registered vendor goes to homepage, and DUNS number has not been verified in Sam.gov
GIven I am a vendor
And I have signed up to the micropurchase platform (via my GitHub account)
And I've entered a DUNS number that is not in Sam.gov
When I go the homepage (https://micropurchase.18f.gov/)
Then I should see the following message
"Your DUNS number was not found in Sam.gov. Please enter a valid DUNS number to complete your profile. Check https://www.sam.gov/sam/helpPage/SAM_Reg_Status_Help_Page.html to make sure your DUNS number is correct. If you need any help email us at micropurchase@gsa.gov"

**Comment by jessieay** [comment]
Pr: https://github.com/18F/micropurchase/pull/533
