### ISSUE TITLE
Vendor sees auctions start/end times and deliver times in ET for current auctions

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#511]
As a vendor who is interested in bidding on an auction, after the auction starts, I want to see when it started, when it will end and the delivery date, so that I can plan my bid, so the system should show me these dates clearly.

Scenario: Vendor views details page for an auction during its bid period
Given I am an authenticated vendor
And there is an auction where bidding has started and has NOT ended
When I view the details page of an auction (https://micropurchase.18f.gov/auctions/[number]
Then I should see in ET when bidding started and will end
And I should see the delivery deadline in ET

**Comment by harrisj** [comment]
This was referenced in PR #524 which has been merged
