### ISSUE TITLE
Vendor sees start/end times and delivery time for auction where bidding has ended, but has not yet been delivered

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#512]
As a vendor who is registered on the micropurchase platform, even though no more bids are being accepted, I still want to see the start time and end time of the auction, as well as the delivery date, so that I can get an idea of how auctions are generally set up, or, if I'm the winner, so that I can see when I need to deliver the work.

Scenario: Vendor looks at auction details page after the auction bidding ends
Given I am an authenticated vendor
And there is an auction where bidding has ended
When I go to the details page for that auction
Then I should see the bidding start and end date as well as the delivery deadline, in ET

**Comment by harrisj** [comment]
This was referenced in PR #524 which has been merged
