### ISSUE TITLE
View page for auction on staging is not working

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#513]
To duplicate
Go to this URL 
https://micropurchase-staging.18f.gov/auctions/19

Expected behavior: I see the details of auction #19 

Actual behavior: I see this screen
<img width="738" alt="screen shot 2016-05-03 at 11 19 33 am" src="https://cloud.githubusercontent.com/assets/100149/14993709/f5a4101e-1120-11e6-9a82-e168fa77196b.png">

**Comment by harrisj** [comment]
This was fixed in #508 after the production hotfix was merged back into develop
