### ISSUE TITLE
Add regression test for issue that broke closed single bid pages

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#516]
fix was merged: https://github.com/18F/micropurchase/pull/508

but there was no test coverage. we should write tests that fail when this regression is re-introduced.

so steps:

- revert code to old state (see #508 for what that looks like)
- write a test that replicates failure (request spec that renders view)
- put code back into new state and confirm that test passes

**Comment by harrisj** [comment]
Agreed. And I apologize. This is my bad.
