### ISSUE TITLE
Preview of "Coming Soon" auctions

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#534]
As a logged in user OR an unknown visitor, I want to see previews of all upcoming auctions so that I see all the potential opportunities for me to participate.

Scenario: I see previews of upcoming auctions on the micropurchase homepage
Given I am a logged in user or an unknown visitor
When I navigate to https://micropurchase.18f.gov/
Then I should see previews of all upcoming auctions
And those previews should contain:
1. The auction title
2. The auction summary
3. An indicator (ribbon) that the auction is "Coming Soon"
4. The starting bid
5. The auction type (sealed-bid or multi-bid)
6. The start date/time
7. The time to start (in days or hours - existing behavior)
And the entire preview should link to the auction show page (https://micropurchase.18f.gov/auctions/[id])
And there should be no "Winning Bid" on an auction that hasn't happened yet

Use the layout/styles as they appear here: https://pages.18f.gov/micropurchase/ but not necessarily that implementation.

**Comment by gemfarmer** [comment]
I assume that these should follow "expiring" auctions?

**Comment by gemfarmer** [comment]
Closed with #616
