### ISSUE TITLE
Preview of "Open" auctions

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#535]
As a logged in user OR an unknown visitor, I want to see previews of all open auctions so that I see and evaluate all the potential opportunities for me to participate.

Scenario: I see previews of open auctions on the micropurchase homepage
Given I am a logged in user or an unknown visitor
When I navigate to https://micropurchase.18f.gov/
Then I should see previews of all open auctions (auctions where bids are being accepted)
And those previews should contain:
1. The auction title
2. The auction summary
3. An indicator (ribbon) that the auction is "Open"
4. The winning bid (see logic below)
5. The auction type (sealed-bid or multi-bid)
6. The end date/time
7. The time to end (in hours or days - existing behavior)
And the whole preview links to the auction details https://micropurchase.18f.gov/auctions/[id]

Logic for showing bid amount:

- multi-bid:
  - vendor has the current winning bid - sees that they have the current winning bid, and the bid amount
  - vendor does not have the current winning bid - sees the current winning bid AND their bid
  - vendor has not bid - sees current winning bid only
- single-bid:
  - vendor has bid - sees their bid
  - vendor has not bid - sees nothing

Use the layout/styles as they appear here: https://pages.18f.gov/micropurchase/ but not necessarily that implementation.

**Comment by gemfarmer** [comment]
Closed with #616
