### ISSUE TITLE
Preview of "Expiring" auctions

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#536]
As a logged in user OR an unknown visitor, I want to see previews of all expiring auctions so that I see and evaluate all the potential opportunities for me to participate.

Scenario: I see previews of expiring auctions on the micropurchase homepage
Given I am a logged in user or an unknown visitor
When I navigate to https://micropurchase.18f.gov/
Then I should see previews of all expiring auctions (auctions where bids are being accepted, and that close in less than 1 day)
And those previews should contain:
1. The auction title
2. The auction summary
3. An indicator (ribbon) that the auction is "Expiring"
4. See the "Current Winning Bid" if it is a multi-bid
5. Bid amount: (see logic below)
6. The auction type (sealed-bid or multi-bid)
7. The end date/time
8. The time to end (in hours or days - existing behavior)
And the whole preview links to the auction details https://micropurchase.18f.gov/auctions/[id]

Logic for showing bid amount:
- multi-bid:
  - vendor has the current winning bid - sees that they have the current winning bid, and the bid amount
  - vendor does not have the current winning bid - sees the current winning bid AND their bid
  - vendor has not bid - sees current winning bid only
- single-bid:
  - vendor has bid - sees their bid
  - vendor has not bid - sees nothing

Use the layout/styles as they appear here: https://pages.18f.gov/micropurchase/ but not necessarily that implementation.

**Comment by gemfarmer** [comment]
@mtorres253 clarifying question: Should the page only contain expiring auctions, or should those simply have priority?

Also, @adelevie @harrisj @jessieay, this seems like a really good front-end/back-end pairing exercise. Any takers for working on this in the next few days?

**Comment by jessieay** [comment]
sure, happy to pair on this.

+1 on question, not entirely clear what this story is asking for. a quick mock might be helpful

**Comment by gemfarmer** [comment]
Closed with #616
