### ISSUE TITLE
Preview of "Closed" auctions

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#537]
As a logged in user OR an unknown visitor, I want to see previews of all closed auctions so that I see and evaluate all past auctions to get a sense of what kinds of opportunities might present themselves in the future.

Scenario: I see previews of closed auctions on the micropurchase homepage
Given I am a logged in user or an unknown visitor
When I navigate to https://micropurchase.18f.gov/
Then I should see previews of all closed auctions (auctions where the end date has passed but delivery date is in the future)
And those previews should contain:
1. The auction title
2. The auction summary
3. An indicator (ribbon) that the auction is "Closed"
4. The winning bid: (See logic below)
5. The auction type (sealed-bid or multi-bid)
6. The end date of the auction
7. The delivery date/time
And the whole preview links to the auction details https://micropurchase.18f.gov/auctions/[id]

Logic for displaying the winning bid:
If the vendor is logged in
- Vendor has won the auction
  - Winning bid AND an indication that the vendor has won the auction
- Vendor has not won
  - Winning bid only

If unknown visitor
- Winning bid only

Use the layout/styles as they appear here: https://pages.18f.gov/micropurchase/ but not necessarily that implementation.

**Comment by gemfarmer** [comment]
@mtorres253 was this supposed to be "Then I should see previews of all closed auctions"?

**Comment by gemfarmer** [comment]
So a status filter could have several options (and corresponding ribbons): 
* upcoming
* open
* closed and pending delivery
* closed and delivered

**Comment by gemfarmer** [comment]
Closed with #616
