### ISSUE TITLE
Index page default sorting

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#538]
As a vendor or unknown user, I want to see information in a particular order, so I know how to find things on the micropurchase homepage

Scenario: Default ordering for the micropurchase homepage
Given I am a registered vendor or an unknown user
When I look at the micropurchase homepage
Then the auction previews should be in descending order by end date timestamp
And the order should go left to right and top to bottom

Note: There are now two columns in the layout so the order will be left->right and top->bottom. https://pages.18f.gov/micropurchase/. This story contemplates just the new grid, not the actual styling

**Comment by gemfarmer** [comment]
@mtorres253 to clarify, descending order by date created, _with the most recently created auction in the top left_?

@adelevie @harrisj @jessieay how is this currently ordered? If/when we add additional filtering, I assume that we would prefer this to be done in javascript?

**Comment by jessieay** [comment]
@gemfarmer currently, index contains published auctions in reverse chron order (using end datetime timestamp)
