### ISSUE TITLE
As a site admin I want CRUD access to each model

### ISSUE THREAD

**Issue by adelevie** [18F/micropurchase#54]
As a site admin 
I want CRUD access to each model
So that I can moderate Auctions, Bids, and Users

[A little higher fidelity stories:]

As a site admin
I want to create/edit Auctions from the web UI
So that I can easily add/edit Auctions and not need SSH access to the server

As a site admin
I want to monitor bids from the web UI
So that I can better understand the auctions (e.g. who is bidding, what prices are the bids, etc)

As a site admin
I want to view a list of users
So that I can know who the users are, and
So that I can begin to verify their DUNS numbers

As a site admin
I want to be able to delete abusive users
So that I can maintain the integrity of the Auctions

**Comment by adelevie** [comment]
@baccigalupi here's my first stab at these, but let's discuss before committing to any of it. cc @blacktm.

**Comment by blacktm** [comment]
We'll break this up into a few new issues.
