### ISSUE TITLE
Header and footer updates

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#544]
In lieu of writing BDD criteria for this small thingie, this story is just to fix the header and footer layout to match this: https://pages.18f.gov/micropurchase/

All content and behavior should remain the same, just laid out differently. 

For the login section, follow up with Andrew for the logged out state, but the logged in state should have an edit profile link somewhere in the layout.

The links in the new footer should match the current links. I think some of them are left out of the prototype

**Comment by gemfarmer** [comment]
For the header, because we currently don't have vendor profile pictures, should I use this part of the header, or leave that area untouched for now?
![screen shot 2016-05-13 at 10 23 20 am](https://cloud.githubusercontent.com/assets/4803473/15252688/bd38a88a-18f4-11e6-87d0-4fc45a14b376.png)

**Comment by gemfarmer** [comment]
If they are all registered github users, we can get that data from the [github api](https://developer.github.com/v3/users/), so maybe we should just go ahead and implement it. If so, this would ideally add the github avatar URL to to the `current_user` data.

@adelevie @harrisj @jessieay thoughts?

**Comment by gemfarmer** [comment]
Also, do we keep the drawer for mobile? Or do we drop the avatar?

**Comment by gemfarmer** [comment]
Alan pointed out that the `avatar_url` can be derived from the id, so `https://avatars2.githubusercontent.com/u/<%= current_user.id %>` works for templating purposes.

**Comment by jessieay** [comment]
👍  to grabbing images from github. don't think that storing / updating avatars should be a high priority for us

**Comment by gemfarmer** [comment]
cool. Note for myself: make sure to use flexbox for footer.

**Comment by gemfarmer** [comment]
@andrewmaier @mtorres253 An additional question here: In the current implementation, the header dropdown has an "Edit Profile". I don't think this should be nixed just yet. Thoughts?

**Comment by andrewmaier** [comment]
@gemfarmer Happy to make this work. I can prototype a dropdown, if that's cool?

**Comment by gemfarmer** [comment]
Responded in slack, but I will double up here for documentation purposes. 

In my mind we wouldn't have a dropdown unless it was necessary. If we can move the "update profile" elsewhere, the area is probably better without a dropdown.
