### ISSUE TITLE
Investigate monitoring and alerts for delayed jobs

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#545]
Based on our discussion this week, we should have some way of monitoring the status of delayed jobs, and there should be alerts when the jobs fail.

This story is to investigate how we can surface these errors to the error logging service

**Comment by mtorres253** [comment]
Reach out for @vv to see if we need to procure any licenses for the solution we select. New Relic and Pingdom are already approved.

**Comment by jessieay** [comment]
@adelevie are you working on this? looks like you moved it into current but are not assigned

**Comment by adelevie** [comment]
I took a first stab at it, but take it from me if you want, @jessieay!

**Comment by jessieay** [comment]
https://docs.newrelic.com/docs/agents/ruby-agent/troubleshooting/sending-new-relic-handled-errors

**Comment by jessieay** [comment]
also found a free plan for airbrake. asking about how we can use that in the new relic admins Slack channel

**Comment by jessieay** [comment]
OK based on a Slack convo with infrastructure ppl, there are not any new relic licenses currently available. Cannot use Airbrake until T&S are approved. So we are stuck. cc @mtorres253  :(

**Comment by jessieay** [comment]
ATO request https://github.com/18F/Infrastructure/issues/621
