### ISSUE TITLE
Validation on auction publish

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#549]
As an admin user, I want to be prevented from creating auctions that don't have all required information, so the system should tell me if required information is missing so that I can provide it

Scenario Outline: User tries to PUBLISH an auction but leaves a mandatory field blank
  Given I am an authenticated admin user
  And I am on the create auction page
  And I have selected "Publish"
  And I leave the [field] blank 
  When I click "Submit"
  Then I should see [message] 
  And the auction should not be published

| field | message  |
|---|---|
| Title | A title is required |
| Summary | An auction summary is required |
| Description | An auction description is required |
| Start Date  | The start date and time for the auction is required |
| End Date  | The end date and time for the auction is required  |
| Delivery Deadline  | The delivery date and time for the auction is required  |
| Start Price  | A starting price for the auction is required  |

    
Note: just start with one flash message containing all the errors and go from there.

**Comment by mtorres253** [comment]
K updated @jessieay

**Comment by jessieay** [comment]
PR for validations: https://github.com/18F/micropurchase/pull/589

@mtorres253 should I add helper text as part of this story or do you want to define that separately?

**Comment by mtorres253** [comment]
I'll define it separately. Thanks @jessieay

**Comment by jessieay** [comment]
oh shoot @mtorres253 I was reading this as "on auction create" not publish. Do you only want these validations to happen when someone is setting an auction to "published" ?
