### ISSUE TITLE
Winners page shows unique bidders per auction

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#564]
As a micropurchase team member, I want to see the number of unique bidders per auction so that I can measure how successful the platform is in involving more and more vendors in the bidding process

Scenario: I see the number of unique bidders per auction on the winners page
Given I am an authenticated admin user
When I navigate to https://micropurchase.18f.gov/auctions/winners
Then I should see a read only field labeled "Unique Bidders per Auction"
And in that field, I should see the number of unique bidders per auction (on average) of all auctions

**Comment by jessieay** [comment]
mock https://micropurchase.mybalsamiq.com/projects/redesignbidflow/prototype/Dashboard?key=7ce1f9e53f0776f57692c2ea4484d505c99922aa
