### ISSUE TITLE
Homepage clean-up

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#582]
Clean-up for Homepage
- [ ] Clean up welcome messaging on logged out view. Reduce vertical height/spacing but keep messaging as is. Try to fit on two lines.
- [ ] Flash messaging goes below
- [ ] Remove welcome section message from logged in view homepage
- [x] Replace "Issues open for bid" with "Auctions"
- [ ] Get rid of top and bottom spacing around the flash messaging on the homepage

**Comment by jessieay** [comment]
https://github.com/18F/micropurchase/pull/674
