### ISSUE TITLE
Separate controllers for API?

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#590]
Sharing controllers for API and non-API is nice bc of lack of duplication but makes controllers noisier. Also feels like we should think about versioning for our API since people seem to be using it now. Having separate controllers would help with versioning because we could namespace them according to version number.

**Comment by adelevie** [comment]
I've been dreading this day.

I do love the lack of duplication in code, tests, and worrying about permissions. On the other hand, perhaps well-defined service objects (which we already do a great job of using) would mitigate most of this duplication and allow us to easily create separate API controllers.

What is the noise you'd like to remove from the controllers, and what else would API separation get us (other than versioning)?

**Comment by jessieay** [comment]
Versioning is probably the top reason to do it -- APIs must be versioned, and while there are many ways to do it, via namespacing is the easiest way to maintain older versions of the API once we move on to newer versions (just no longer touch older controllers after that)

The second reason is that, even though our controllers aren't huge right now, the would be even slimmer if they only handled HTML or JSON. Also, since we are currently sharing controllers, there is a tiny bit of weirdness where we sometimes instantiate objects for the API but don't them for HTML. eg: https://github.com/18F/micropurchase/blob/70120be3aac38a68eb5438e3210170533b60ded2/app/controllers/admin/auctions_controller.rb#L62

**Comment by harrisj** [comment]
I will admit that I think we should split them too, even though it breaks @adelevie's heart. It might be interesting too that it'll simplify the authentication logic within ApplicationController, since each controller would use its own type.

**Comment by jessieay** [comment]
This might be a good thing to do while @mtorres253 is out of town next week since it will take a few PRs to get through all the controllers and is a refactor rather than product change

**Comment by jessieay** [comment]
We did this! Closing
