### ISSUE TITLE
Validation on auction create

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#592]
As an admin user, I want to be able to create auctions, but I don't want to have to have all the info ready when I create them. So, the system should just require the minimum amount of info that will allow me to recognize that the auction I create (so that I don't create duplicates and so that I can update the correct auction later.

Scenario Outline: User tries to CREATE an auction but leaves a mandatory field blank
  Given I am an authenticated admin user
  And I am on the create auction page
  And I have selected "Publish"
  And I leave the [field] blank 
  When I click "Submit"
  Then I should see [message] 
  And the auction should not be published

| field | message  |
|---|---|
| Title | A title is required |
| Start Date  | The start date and time for the auction is required |
| End Date  | The end date and time for the auction is required  |

    
Note: just start with one flash message containing all the errors and go from there.

**Comment by jessieay** [comment]
PR: https://github.com/18F/micropurchase/pull/589
