### ISSUE TITLE
Auction form field placeholder text

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#593]
As an admin user, I want to make sure that I'm putting the right info in the right inputs when I create or edit an auction. So the system should offer some hints.

Scenario Outline: User tries to CREATE an auction and sees form input hints
  Given I am an authenticated admin user
  When I am on the create auction page
  Then I should see a placeholder `<message>` for each `<field>`

Scenario Outline: User tries to EDIT an auction and sees form input hints
  Given I am an authenticated admin user
  When I am on the create auction page
  Then I should see a placeholder `<message>` for each `<field>`

| field | message  |
|---|---|
| Title | A short description of the work |
| Summary  | A brief summary of the auction and rules |
| Description  | Add any context that might help the bidder, as well as language used, acceptance criteria and a definition of done |
| Start Price  | Specify the bidding start price |
| GitHub Repo  | The GitHub repo where the winner's pull request is to be filed |
| GitHub Issue  | The GitHub issue corresponding to this auction |
| Published | Selecting publish will make the auction visible to the public |
| Delivery URL | The URL of the pull request fulfilling the auction requirements |

**Comment by harrisj** [comment]
Do we want to do these as hints underneath the form input or as text within the boxes? If the later, make sure they can't be published with that text.

**Comment by jessieay** [comment]
When @mtorres253 and I discussed this, we were looking at `placeholder` style from simpleform

![screen shot 2016-05-19 at 10 54 55 am](https://cloud.githubusercontent.com/assets/601515/15549482/9297222a-2261-11e6-8a39-5796477f540e.png)

**Comment by jessieay** [comment]
Closed via https://github.com/18F/micropurchase/pull/624
