### ISSUE TITLE
Potential auction batch

### ISSUE THREAD

**Issue by adelevie** [18F/micropurchase#626]
This issue lists *potential* upcoming auctions for the platform. Nothing here is guaranteed to be put up for auction.

- [Adding Active Start and End Dates to Tock Projects](https://github.com/18F/tock/issues/352) (Tock)
- [Handle regular policy reminders](https://github.com/18F/dolores-landingham-bot/issues/180) (Dolores Landingham Bot)

**Comment by jessieay** [comment]
these were both done! should we close this issue @adelevie ?

**Comment by adelevie** [comment]
Yup!
