### ISSUE TITLE
Add jasmine tests to Travis 

### ISSUE THREAD

**Issue by gemfarmer** [18F/micropurchase#628]
I just noticed that the auctions/winners page is broken in prod, likely because the Jasmine tests aren't configured in Travis! 

As a corollary to this Travis issue, all code should be updated so that the Jasmine tests pass. This will likely just mean renaming some methods in the JS, as there were several recent renaming PRs.

**Comment by jessieay** [comment]
Can run jasmine with konacha https://github.com/18F/C2/blob/master/Rakefile#L11

**Comment by jessieay** [comment]
jasmine ci may be best option (vai brian) https://github.com/jasmine/jasmine-gem#usage

**Comment by jessieay** [comment]
this is done!
