### ISSUE TITLE
ended_at not showing up in API

### ISSUE THREAD

**Issue by gemfarmer** [18F/micropurchase#635]
Recently a few of the fields changed in the API. 

`end_datetime` --> `ended_at`
`start_datetime` --> `started_at`

This isn't reflected in the api. [auctions.json](https://micropurchase.18f.gov/auctions.json) returns json with no `ended_at` attribute present:

<img width="427" alt="screen shot 2016-05-31 at 3 03 09 pm" src="https://cloud.githubusercontent.com/assets/4803473/15688735/146c1952-2741-11e6-9428-7ac02b765e4a.png">

**Comment by jessieay** [comment]
this is no longer an issue - closing!
