### ISSUE TITLE
Bid confirmation page shows when bid is accepted

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#648]
As a vendor who is bidding on an auction, I want to get a message from the system if my bid is not accepted.

Scenario: Vendor submits an invalid bid
Given I am a logged in vendor
And there is an auction
And I am eligible to bid on the auction
When I submit a bid
And the bid is invalid
Then my bid should not be accepted
And I should stay on the bid page
And I should see the appropriate error message

Note: Currently this is broken. for some reason, when I make a bid on an auction, and my bid is invalid, I'm taken to the confirmation page anyway and I see a rails error. There are already error messages, they just don't show because the user is directed to another page

**Comment by mtorres253** [comment]
@jessieay Is this already fixed? I'm seeing the correct behavior on staging.

**Comment by jessieay** [comment]
@mtorres253 yup I fixed this yesterday before I wet home and Jacob merged last night

**Comment by jessieay** [comment]
Pr here https://github.com/18F/micropurchase/pull/645
