### ISSUE TITLE
Charts aren't showing on the winner's page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#649]
Go to https://micropurchase.18f.gov/auctions/winners

Expected behavior:
Charts appear on the page

Actual behavior:
They are no longer there

See screenshot
![screen shot 2016-06-02 at 11 23 42 am](https://cloud.githubusercontent.com/assets/100149/15756086/8204cc1a-28b4-11e6-95be-672779f3f959.png)

**Comment by jessieay** [comment]
PR: https://github.com/18F/micropurchase/pull/680
