### ISSUE TITLE
Delivery deadline edits not being applied

### ISSUE THREAD

**Issue by harrisj** [18F/micropurchase#654]
This is in the Auction parser and note the typo. 

```
def delivery_due_at
    if auction_params.key?(:due_in_days) && auction_params[:due_in_days].present?
      real_days = auction_params[:due_in_days].to_i.business_days
      end_of_workday(real_days.after(ended_at))
    elsif auction_params[:deliery_deadline]
      parse_datetime("delivery_due_at")
    end
  end
```

This functionality is used when an administrator edits an existing auction (for new auctions, they provide a deadline as a number of days). Annoyingly it does not seem to have been caught by a test. Fix this with a working test too.

**Comment by jessieay** [comment]
This was fixed -- closing!
