### ISSUE TITLE
Verify that monitoring works on production

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#657]
We have NewRelic on production but we should verify that it's working. This story is to make sure that the following situations trigger alerts

- [x] Auto-emails don’t get sent
- [x] SAM.gov job doesn’t run
- [x] Exceptions being raised when people are trying to bid

**Comment by jessieay** [comment]
OK, got new relic alerts set up so that the developers are emailed when there is an error

related PR here https://github.com/18F/micropurchase/pull/677

more info on how New Relic monitors delayed jobs: https://docs.newrelic.com/docs/agents/ruby-agent/background-jobs/delayedjob
