### ISSUE TITLE
.csv export of vendor data

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#658]
As an admin user, I will sometimes want to get an export of vendor data so I can do things like send bulk emails to the vendors. So the system should allow me to do this

Context:
Given I am a logged in admin user

Scenario: I see a link on the users page to dowload a .csv
When I am viewing the users page https://micropurchase.18f.gov/admin/users
Then I see a link labeled "Download CSV" next to the "Users" header

Scenario: I download a .csv containing users name and email
When I click on the "Download CSV" link
Then a CSV file should be downloaded to my computer
And the CSV column headers should be "First Name", "Last Name" and "Email Address"
And under each column header I should see the first name, last name and email address of each user

**Comment by harrisj** [comment]
I have started work on this. Currently we do not separate user names into a first name and last name (and this is often problematic to do after the fact). Is it okay if we just return a single name field?

**Comment by harrisj** [comment]
One other question: do we want this to download ALL users or just non-admin users?

**Comment by adelevie** [comment]
Good question. It might be helpful for all admins to still get the same
emails as everyone else.
