### ISSUE TITLE
Update small business status of users on production

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#662]
So that we have a current sense of how many of our vendors are small businesses, let's run a check against Sam.gov for existing users, then let the delayed job handle future updates.

**Comment by jessieay** [comment]
Just went through the data on prod for this. Had to do it al manually bc I think we were dealing with API timeouts when I iterated through users programatically. ugh!

Anyway, here are the stats:

Sam users: 85
Small business users (subset of Sam): 57
Non-small business users who are in Sam: 28
Non-Sam users: 118
