### ISSUE TITLE
P-card payment method is specified for an auction

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#663]
As an admin user, I want to be able to prevent automatic CAP payment requests when the auction is being paid with another P-card, so I should be able to specify when automatic payments can be made

Scenario: Admin specifies whether an auction is paid through an 18F P-card
Given I am a logged in admin
When I am creating an auction
Then I should see a checkbox labeled "Use 18F P-card"
And that checkbox should be CHECKED by default
And I should be able to uncheck it
And I should be able to save my changes

**Comment by jessieay** [comment]
moved back to "backlog" bc want to discuss naming before implementing 

https://18f.slack.com/archives/micropurchase-dev/p1465335446000118

**Comment by jessieay** [comment]
in slack we settling on a `pcard` enum field 

![screen shot 2016-06-07 at 3 02 35 pm](https://cloud.githubusercontent.com/assets/601515/15876215/ebcfe4f8-2cc0-11e6-8d5b-dd22ec27e6aa.png)

**Comment by jessieay** [comment]
@mtorres253 did this as as dropdown rather than a checkbox for reasons discussed in Slack

screenshot on PR https://github.com/18F/micropurchase/pull/681
