### ISSUE TITLE
Customer index page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#668]
As an admin, I want to see a list of customers currently in the system, so there should be an index page listing them

Scenario: I see existing customer agencies on customers page
Given I am a logged in admin
And I'm on the admin homepage
And there are clients in the system
Then I should see a link to "Customer Agency"

When I click on that links I should go to https://micropurchase.18f.gov/admin/customers
And I should see a header "Customer Agency"
And I should see the clients listed alphabetically
And I should see the customer agency name, the contact name and the contact email

**Comment by jessieay** [comment]
Closed via #809
