### ISSUE TITLE
System checks CAP to get payment date

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#669]
As an admin I want to see when someone was actually paid via CAP in relation to when the auction was delivered, so that I can measure the effectiveness of the payment method

Scenario: Admin sees payment date on auction view form for payment made via CAP
Given I am a logged in admin
And there is an auction that has been successfully accepted
And a payment request was successfully made via CAP
And the payment was made to the vendor
When I go to the show page for the auction (https://micropurchase.18f.gov/admin/auctions/24)
I should see the date the payment was made

As an vendor I want to see when someone was actually paid via CAP in relation to when the auction was delivered, so that I can get a sense of how quickly winners get paid in general.

Scenario: Vendor sees payment date on auction view form for payment made via CAP
Given I am a logged in vendor
And there is an auction that has been successfully accepted
And a payment request was successfully made via CAP
And the payment was made to the winning vendor
When I go to the show page for the auction (https://micropurchase.18f.gov/auctions/[24])
I should see the date the payment was made

As an unknown visitor, I want to see when someone was actually paid via CAP in relation to when the auction was delivered, so that I can get a sense of how quickly winners get paid in general. (This might motivate more vendors to sign up, and more customers to use the micropurchase platform)

Scenario: Unknown visitor sees payment date on auction view form for payment made via CAP
Given I am an unknown visitor to the micropurchase site
And there is an auction that has been successfully accepted
And a payment request was successfully made via CAP
And the payment was made to the winning vendor
When I go to the show page for the auction (https://micropurchase.18f.gov/auctions/[24])
I should see the date the payment was made

Note: If it's not there already, let's add a pull request to Cap to add this information. Add the check to the once a day update. Make sure this is monitored by NewRelic

**Comment by jessieay** [comment]
https://github.com/18F/C2/blob/master/app/serializers/proposal_serializer.rb

so we will want to look at the “purchase” step https://github.com/18F/C2/blob/master/app/serializers/step_serializer.rb
and see if it has a status of `completed`
looks like there’s not timestamp for that — I can do a PR to add when that card comes up
there is a `completed_at` timestamp in the C2 API for steps

**Comment by jessieay** [comment]
PR to C2 to add `completed_at` to API: https://github.com/18F/C2/pull/1343
