### ISSUE TITLE
Billable to: field data from Tock

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#672]
As an admin, I want to store accurate information about who is paying for the auction (with whom we have the agreement), so the system should limit my options to just those that actually exist

Scenario: I select a Tock project to bill to when I create a new auction
Given I am a logged in admin
When I'm creating a new auction
Then I should see a select dropdown labeled "Billable To"
And that dropdown should contain all Tock projects here https://tock.18f.gov/api/projects.json
And I see whether the project is billable or not billable
And this field is required
And I should be able to save this data

https://tock.18f.gov/api/projects.json

Note: ensure that old data conforms to our new way of doing things

**Comment by jessieay** [comment]
Opened an issue on Tock with some API questions here https://github.com/18F/tock/issues/363

**Comment by mtorres253** [comment]
Project mapping:

Tock -> Tock(62)
Open Opportunities -> Custom Partner Solutions / OCSIT / Open Opportunities (206)
Micropurchase -> Acquisition Services / Marketplaces / Micropurchasing (237)
GP - API Program - GP - API Program (92)
Consulting / Marketplaces / Tools -> [blank]
Playbook in Action -> GP - Playbook in Action (83)
