### ISSUE TITLE
Suggest updating "Learn more about this experiment" link

### ISSUE THREAD

**Issue by brittag** [18F/micropurchase#692]
It looks like right now the homepage "Learn more about this experiment" link goes to an individual blog post (https://18f.gsa.gov/2015/11/06/micro-purchase-lessons/) that has some great information but doesn't quite provide a summary upfront of what the micropurchase experiment is (or what's been happening recently). I'd suggest linking to https://18f.gsa.gov/tags/micro-purchase-platforms/ or to a new page that has a plain language summary of the experiment with links to more information such as blog posts. :)

**Comment by brittag** [comment]
(Or maybe "Learn more about this experiment" should be a link to https://micropurchase.18f.gov/faq - which I just noticed linked in the footer?)

**Comment by jessieay** [comment]
we updated this to go to https://micropurchase.18f.gov/insights -- thanks for filing the issue, @brittag ! closing
