### ISSUE TITLE
New layout and styling

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#694]
This story is to re-do the layout/styling of the existing auction show page. This will be for both the admin and vendor view. For now, keep the existing right rail, just adapt to the new layout. 

- [ ] Change the breadcrumb language to "Auctions -> [Auction name]"
- [x] Bar beneath auction title with the "Auctions Bids" nav
- [x] Ribbon with the auction status
- [x] Font and styling changes

https://pages.18f.gov/micropurchase/auctions/show/

Note: @andrewmaier will collaborate with developer and clean up the styles.

**Comment by jessieay** [comment]
@mtorres253 wondering if we really need the breadcrumbs here -- people can click on the 18F logo to go back to the homepage. What do you think>
