### ISSUE TITLE
Add feature specs to exercise all views and articulate user flows

### ISSUE THREAD

**Issue by baccigalupi** [18F/micropurchase#72]
Currently there are controller specs that test database changes and which view is rendered. There have been easy refactoring generated bugs getting through because the views are not being exercised in the tests yet. Also, the typical user story flows are not being captured in the unit tests.

This chore aims to capture user flows and make sure all the views get exercised in the test suite. More than likely controller specs will be eliminated in this process.

**Comment by adelevie** [comment]
Fixed in #73.
