### ISSUE TITLE
Use consistent naming

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#735]
We use `micro-purchase` in tweets and emails but the platform def uses `Micropurchase`. Let's settle on one and use it everywhere so we don't end up like Communicart/Cap/C2 (lol 😄 )

**Comment by adelevie** [comment]
I think for all user-facing copy, "micro-purchase" is what we should use, but for the repo name (maybe) and for names in source code, "micropurchase" is fine.

**Comment by jessieay** [comment]
why not use the same thing everywhere, @adelevie ? that seems confusing to me

**Comment by adelevie** [comment]
because ruby doesn't love `-` in names and camel casing might be even more confusing

**Comment by harrisj** [comment]
I think unfortunately it's called `micro-purchase` in the legislation, right?

**Comment by jessieay** [comment]
Done!
