### ISSUE TITLE
Links on action items page are not working

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#738]
To duplicate
Navigate to https://micropurchase.18f.gov/admin/action_items
Click on the "Tock superusers should be able to enter 0-60 hour weeks" url

Expected behavior: You navigate to https://micropurchase.18f.gov/admin/auctions/10

Actual behavior: You see a page not found error

<img width="1229" alt="screen shot 2016-06-20 at 11 48 42 am" src="https://cloud.githubusercontent.com/assets/100149/16206369/f8eeae14-36dc-11e6-94c0-37179506133e.png">

**Comment by jessieay** [comment]
ah yup I noticed that too.
