### ISSUE TITLE
Link to Winners page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#750]
As any viewer of the micropurchase platform, I want to see data about how the micropurchase platform is performing, so that I can understand things that can help me decide whether and when to participate in an auction and what to expect

Scenario: A visitor is viewing the micropurchase homepage
Given I am a visitor to the micropurchase site
When I view any page
Then I should see a link labeled "View marketplace insights >>."

When I click on that link
Then I should navigate to https://micropurchase.18f.gov/winners

Note: Put in the welcome message - replace the "learn more about this experiment" link (see mock) and also put in the footer so that the link is on every page

![screen shot 2016-06-29 at 11](https://cloud.githubusercontent.com/assets/100149/16467609/f306b484-3dfc-11e6-8a61-b4f111219229.png)

**Comment by jessieay** [comment]
@mtorres253 what about putting it in the little dropdown on upper righthand? that is only for logged in users, but we could also link to it in the footer ?

**Comment by jessieay** [comment]
@mtorres253 you said you were going to do a quick mock for this?

**Comment by mtorres253** [comment]
Yes, I would just put the link in the welcome message (replace "Learn more about this experiment") and the footer for now.
