### ISSUE TITLE
Email sent to vendor if credit card URL is not on file when auction is accepted

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#770]
As a vendor I want to be apprised if my work was accepted and I cannot be paid, so the system should do that for me

Scenario: Vendor receives email asking them to add a credit card URL to their profile
Given I am a registered vendor
And there is an auction that I have won and delivered
And I do not have a payment URL specified in my profile
When the auction is accepted (admin sets the result to "accepted")
Then the system sends an email to the vendor
And no payment action is taken
And the email should have the following values
From: micropurchase@gsa.gov
To: [vendor email]
Subject: Please update your profile so Micro-purchase can pay you for your great work!
Dear [vendor name]

A payment of $[amount] is pending release regarding work you recently completed on [auction name]. In order to take receipt of payment, you will need to first add a credit card URL to your profile. Please go to  https://micropurchase.18f.gov/profile to update this information. 

Questions? Please contact us at microupurchase@gsa.gov

"Sincerely,"

"The 18f Micropurchase team"

Note: This story includes changing https://micropurchase.18f.gov/edit_user to https://micropurchase.18f.gov/profile

**Comment by adelevie** [comment]
Doing the following refactoring as a pre-cursor:

(not truly a feature spec since this describes application behavior, but not user-facing behavior)

When an `auction.end_time` is created, a delayed job task is queued up, for that time, which invoked a generic job called something like `AuctionEnded.new(auction).perform`.

When an `auction.end_time` is updated, the corresponding job is updated to run at the new `.end_time`.

When an `auction.end_time` is deleted (or an entire auction is), the corresponding job is deleted.

**Comment by adelevie** [comment]
Following this, we could develop a somewhat standard pattern, with a class called `AuctionAccepted`, which would wrap all of the tasks that need to happen when an auction is accepted.

**Comment by mtorres253** [comment]
Changed from address to be consistent with other emails - admin@micropurchase.gov

**Comment by adelevie** [comment]
Wait we don't own the micropurchase.gov domain.

**Comment by jessieay** [comment]
@mtorres253 after user updates credit card URL, I assume *that* is when the purchase request should get updated? 

Right now we update purchase request in C2 as soon as accepted. In that update we include winning bidder details, including credit card url (see /18F/micropurchase/blob/develop/app/services/update_c2_attributes.rb) 

This story was written before when we created the purchase request after acceptance so it refers to not creating the purchase request after the credit card url is updated.

**Comment by mtorres253** [comment]
@jessieay Yes,I think if the auction is accepted, and the credit card URL is in place, then an update is made to C2
