### ISSUE TITLE
Auction approval request to CAP

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#771]
As an admin user, I want to make sure that there is budget for a given auction before I make it public, so if there is a way for the system to alert the budget holder to the upcoming auction before it goes live, then the system should do that

Scenario: Admin sees "Request Auction Approval" button on create auction form
Given I am logged in as an admin
And I have successfully created an auction
And the auction uses the default payment method (CAP)
When I go to the edit form for that auction https://micropurchase.18f.gov/admin/auctions/[id]/edit
Then I should see a button labeled "Request Auction Approval"

Scenario: Notification to CAP that an auction will be published
Given I am logged in as an admin
And a draft auction exists
And the auction uses the default payment method (CAP)
When I click on the request approval button
Then a request is made to CAP
And the request should specify the start price of the auction
And I should see an indication that approval was requested

Scenario: Admin tries to publish an auction without having requested approval
Given I am logged in as an admin
And a draft auction exists
And the draft auction uses the default payment method (CAP)
And I have not requested approval for the auction
When I try to publish the auction
Then I should see an error "You must request approval for this auction before publishing"
And the auction should not be published

Note: let's talk about the MVP implementation of this feature

**Comment by jessieay** [comment]
When creating an auction that uses the default P card you cannot set the auction to "published" until there is cap proposal url

the cap_proposal_url field is visible but not update-able

there is a link in the auction form called "create c2 proposal" that creates a proposal in C2

once the proposal is created, that link goes away

when the cap proposal is created, that field is filled in

when cap request is approved, the "publish" option is available

system checks for approval hourly

**Comment by jessieay** [comment]
PR https://github.com/18F/micropurchase/pull/822
