### ISSUE TITLE
Admin sees all data on auction show page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#773]
As an admin user, I want to see all information about an auction on the auction show page, so that I don't have to go to the edit page.

Scenario: Admin sees <data_point> on auction show page
Given I am logged in as an admin
And there is a given auction
When I go to the show page for that auction
Then in addition to what I already see
I should see a section labeled <data_label>
And in that a section I should see the value for <data_point> if there is one

| Data Point | Data Label |
| :---- | :---- |
| auction_type | Auction Type |
| auction_github_repo | Github repo URL |
| auction_issue_url | Github issue URL |
| auction_delivery_due_at | Delivery deadline date and time |
| auction_start_price | Starting price |
| auction_purchase_card | Purchase card |
| auction_cap_proposal_url | Cap proposal URL |
| auction_published | Published status |
| auction_delivery_url | Delivery URL |

Note: Use the same layout as the vendor view. Put the admin specific stuff below the vendor stuff in the right rail (gray box)

**Comment by jessieay** [comment]
should we add an edit link here, too?
