### ISSUE TITLE
Customer gets email on auction acceptance

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#779]
As an admin user, I want to automatically notify any customer who is using their own p-card when an auction is accepted, so that they can pay the vendor, so the system should do this for me.

Scenario: Customer using their own p-card gets email when auction is accepted
Given I am a logged in admin
And an auction for that customer has been successfully delivered
And the winning vendor has a Credit Card URL
When the auction is accepted
Then the system generates an email
From address: admin@micropurchase.gov
To address: [contact email]
Subject: Your auction has been successfully delivered!
Body: Dear [contact name]
Your auction [auction name] has been successfully delivered! The winning vendor is [vendor name] and the final price of the auction is [xxxx]. 

You may examine the delivered code here: [delivery_url]

Questions? Contact micropurchase@gsa.gov.

Sincerely,

The 18f Micropurchase team

Note: Let's discuss details and break down

**Comment by jessieay** [comment]
@mtorres253 do we own admin@micropurchase.gov ? If not, I say we send it from `micropurchase@gsa.gov` so replies are captured properly...

**Comment by jessieay** [comment]
also, not sure " You will need to pay the vendor using your own P-card." makes sense -- eg: if the client is Tock, they are not going to use their own p-card. Maybe different text for email based on pcard used for auction?

**Comment by mtorres253** [comment]
Yes, cause Tock will be using our P-card

**Comment by jessieay** [comment]
another caveat -- customers won't always have a `name` -- do we want to require the name field or remove the greeting? would be weird if there is no name

**Comment by jessieay** [comment]
PR https://github.com/18F/micropurchase/pull/830

**Comment by mtorres253** [comment]
Taking out the reference to P-card. We can add this in a future story if indicated.
