### ISSUE TITLE
Payment action is taken when vendor adds credit card URL after auction is accepted

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#780]
As an admin, I want the system to initiate payment action for an auction when all information is available, so when the auction is accepted, and the winning vendor has a credit card URL on file, the payment action should be started automatically

Scenario: Vendor adds credit card URL after auction is accepted
Given I am a logged in vendor
And I have successfully delivered on an auction
And I don't have a credit card URL on file
And the auction has been accepted
When I add a credit card URL to my profile
Then the payment action for that auction should automatically occur (update previous CAP request or email to customer agency)

Generic concept of payment method may need to be added? This could result in some refactoring.

**Comment by jessieay** [comment]
added a question on another issue that is more related to this story: https://github.com/18F/micropurchase/issues/770#issuecomment-231205480
