### ISSUE TITLE
I see a section for rejected auctions on the actions page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#790]
As an admin, I want to quickly see which auctions were rejected so that I can quickly see any patterns tha, so the system should show that to me.

Scenario: I see a rejected section on the action items page
Given I am logged in as an admin
And there are auctions that have been rejected
When I go here https://micropurchase.18f.gov/admin/action_items
Then I should see a section labeled "Rejected Auctions"
And in that section I should see all rejected auctions listed (most recent first)
And I should see the name of each auction
And I should see the URL of the pull request (if there is one)
And I should see the name of the vendor who submitted the pull request
And I should see the delivery date
And I should see the date it was rejected

**Comment by harrisj** [comment]
This should be doable, but currently all items on the dashboard have the same columns:

* Title
* Delivery Deadline
* Delivery URL
* Result
* CAP URL
* Paid?

I wonder if we should consider changing that.

**Comment by mtorres253** [comment]
Yes, we should consider changing that. I feel like each case would require different data. I'm trying to look at each thing individually and go from there.

**Comment by adelevie** [comment]
Agree on different columns for different states. Some other enhancements to consider:

1. Horizontal, Trello-esque layout to track progress from left to right.
2. Allow action items to be dealt with inline, so that an admin need not click edit and view an entire auction when only a single form element matters for a given action. Example:

```
Feature: Admin can mark an auction as accepted inline in action items in admin panel

Scenario: Marking auction as accepted
Given I am logged in as an admin
And there is an auction that needs evaluation
And I visit the action items page in the admin panel
Then I should see a button with the text "Reject"
And I should see a button with the text "Accept"
When I click the button with the text "Accept"
Then I should see that the auction is not in the Evaluation Needed section of action items
```

3. Remove/rethink some sections since their steps are now automated. I'm looking at "Payment needed", but there might be others.

**Comment by harrisj** [comment]
I think those are good ideas, but out of the scope of this PR. Still...

**Comment by harrisj** [comment]
Going to do another PR for the table that @mtorres253 requested
