### ISSUE TITLE
Add skills to auctions

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#794]
We have a graph on winners page about languages. It is currently based on static data that does not come from our DB or API. 

We should be able to tag auction with languages in order to calculate these numbers. Would also help vendors know what to bid on.

Languages:
1. Ruby
2. Python
3. Javascript
4. Coffeescript
5. HTML
6. HAML
7. CSS
8. SCSS
9. Go script

1. Add tag selectors to auction create/edit forms and let admins associate one or more languages with an auction
2. Show on the vendor profile page what languages that vendor has bid on. At a high level and in the bid history
3. Show the languages on the insights page (actually hook it up to real data)

![screen shot 2016-07-08 at 4 07 24 pm](https://cloud.githubusercontent.com/assets/100149/16703867/10516b8a-4526-11e6-971c-bfa81c5623e2.png)

**Comment by harrisj** [comment]
Do you think we should create a `Language` model and a `Framework` model and associate them? Or should we instead consider some sort of generic tags model and language and framework are types of tags (or we just tag with strings and leave it untyped?)

**Comment by mtorres253** [comment]
We can just use tags for now I think. We can discuss as a group, but that
would be the easiest thing to do.

On Wed, Jul 6, 2016 at 7:19 AM, Jacob Harris <notifications@github.com>
wrote:

> Do you think we should create a Language model and a Framework model and
> associate them? Or should we instead consider some sort of generic tags
> model and language and framework are types of tags (or we just tag with
> strings and leave it untyped?)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/micropurchase/issues/794#issuecomment-230786005>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGHNaeRlZxnHR9m6zQQKuU5-DPKwXQ9ks5qS7l3gaJpZM4JAgRm>
> .
>



-- 
Michael Torres
Product Lead, Micropurchase Platform
18F
(415) 920-3205

**Comment by jessieay** [comment]
@harrisj Given that we want to do stats with these, I think making a table would be logical. I think we can put both languages and frameworks in the same table.

**Comment by jessieay** [comment]
Looking at the chart we have for this now, would it make sense to assume that each auction represents just one language? https://micropurchase-staging.18f.gov/insights#donut-by-language

**Comment by mtorres253** [comment]
I don't think the chart necessarily assumes that. We can find another way
to visualize if this doesn't work but I think it will.

On Thu, Jul 7, 2016 at 2:01 PM, Jessie A. Young <notifications@github.com>
wrote:

> Looking at the chart we have for this now, would it make sense to assume
> that each auction represents just one language?
> https://micropurchase-staging.18f.gov/insights#donut-by-language
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/micropurchase/issues/794#issuecomment-231206135>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGHNfKpApPC4GbE8xscKsoMRTA3VJIqks5qTWklgaJpZM4JAgRm>
> .
>



-- 
Michael Torres
Product Lead, Micropurchase Platform
18F
(415) 920-3205

**Comment by jessieay** [comment]
puts languages into a bar chart. 

put projects copy into righthand column
