### ISSUE TITLE
Update content for vendors

### ISSUE THREAD

**Issue by andrewmaier** [18F/micropurchase#798]
As a vendor, I want to know what "Credit Card URL" means, and I want to know how I get paid, so there should be instructions to do that somewhere on the site

Stripe
SquareCash (Cashtag)

https://github.com/cwarden/pay

**Comment by adelevie** [comment]
No to PayPal ... it's not a credit card URL.

**Comment by adelevie** [comment]
Key points:

- any and all credit card processors are acceptable, we don't care
- there are some easy options out there, including Stripe and SquareCash
- previous winners have used: (Stripe + cwarden/pay + heroku, etc)
- Let us know if you're interested in PayPal

**Comment by andrewmaier** [comment]
https://docs.google.com/document/d/1KvfOICKTPIFBLM_t1eGj8saBF_dYZjWjrE7mx9R3R9A/edit#

**Comment by neilmartis** [comment]
@andrewmaier @adelevie I have setup a stripe account for the same.How would I know which url is right one?any suggestions?

**Comment by mtorres253** [comment]
@andrewmaier SquareCash is not working now (for some reason not accepting purchase cards), so I would just explain how to set up a Stripe URL and point to cwarden's pay project. And we can mention that we are looking into alternate payment methods like SquareCash

**Comment by mtorres253** [comment]
Also updating the title of this story so that we can work on a wholistic experience for the user (they don't have to go to three different pages to get information about how to participate.

**Comment by andrewmaier** [comment]
We're presently thinking of using some kind of progressive disclosure to do this. Pages such as our About page, our post-sign up page, policies page, etc. Additionally, we'll likely want to create a "docs" section of the site that serves as a repository of helpful content.

**Comment by mtorres253** [comment]
Let's close up policies and all other vendor facing pages this week so that we can deploy them before the next auction
