### ISSUE TITLE
Payment is not being reflected on action items page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#803]
To duplicate

Go to https://micropurchase.18f.gov/admin/action_items

Expected behavior: The following auction should show as paid
Actual behavior: It shows as pending payment
![screen shot 2016-06-29 at 10 30 26 am](https://cloud.githubusercontent.com/assets/100149/16463265/e0d1cf0a-3de9-11e6-8215-0de8d8b5700c.png)

**Comment by jessieay** [comment]
@mtorres253 this hasn't been marked as paid in C2 so it is not marked as paid in Micropurchase https://cap.18f.gov/proposals/4474#

**Comment by jessieay** [comment]
NM was looking at wrong item. Tock request is now paid and was updated properly in MP.
