### ISSUE TITLE
Search lookup for Tock "Billable to" field

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#819]
As an admin user, I want to easily find the Tock categories I'm billing when I create or edit an auction. So the system should allow me to look up a tock category.

Scenario: I look up a Tock category on the create auction form
Given I am logged in as an admin
And I am creating a new auction
And there are Tock categories in the system
When I type into the Billable to field
Then the system should show me the tock categories that match my search
And those categories should appear in a dropdown below the field
And they should be ordered alphabetically (by the first word)
And my view should be limited to 10 options at the most.

When I keep typing
Then the options should update to match the string I'm typing

When I select one of the options that are shown to me
Then that Tock category should populate the "Billable To" field
And the dropdown should disappear

NOTE: Behavior on edit is the same. Dropdown appears as I start typing in the Billable To field. Options adjust as I keep typing and when I select one of the options, it appears as the value for the "Billable To" field

**Comment by jessieay** [comment]
https://github.com/18F/micropurchase/pull/831

**Comment by jessieay** [comment]
closed via 831
