### ISSUE TITLE
Link to the SAM status tracker page has changed

### ISSUE THREAD

**Issue by brentschneider** [18F/micropurchase#829]
Via the getting started landing page, the link to the **SAM status tracker** seems to have changed, resulting in a 404 error.

Seems the new URL is something along the lines of: https://www.sam.gov/portal/SAM/?navigationalstate=action#1

**Comment by jessieay** [comment]
Thanks for reporting this, @brentschneider ! PR for fix is here: https://github.com/18F/micropurchase/pull/871
