### ISSUE TITLE
Skills chart on the insights page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#836]
As a visitor to the site, I want to know overall which skills are represented in the past auctions, so i should easily be able to see that in a chart 

Scenario: I see a programming langauge chart on the micropurchase insights page
Given I am a visitor to the site
When I am looking at the insights page
Then i should see a chart labeled "Skills"
And in that chart I should see a list of all skills that have been associated with auctions
And for each language I should see the number of auctions
And the list should be in order of most popular skill to least

![screen shot 2016-07-12 at 1 10 56 pm](https://cloud.githubusercontent.com/assets/100149/16781895/268e85b8-4832-11e6-9bc6-18a53e4d4171.png)

**Comment by jessieay** [comment]
@mtorres253 screenshot upload in description of this ticket failed - can you try again?

**Comment by mtorres253** [comment]
@jessieay done
