### ISSUE TITLE
New sign-up/sign-in flow

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#838]
This epic is to re-do the sign-up flow so that vendors have a clear idea of what's going on, and so that they don't have to take so many steps. There was some confusion expressed in our user interviews around authenticating with GitHub multiple times. 

So, if they are logged out, and the just need to log back in, if we can remember them, we should

When they are signing up for the first time they should be able to authenticate with GitHub, and indicate that they understand the nature of the micro-purchase platform:

1. It is an experiment
2. It is public (usernames, DUNS numbers, and bid amounts will be public after the auction ends)
3. Understand a bit about what to expect with the Sam.gov sign-up process
4. Understand that they need to give us a Credit Card URL to get paid

The profile page should also be enhanced so that they can better understand what information we need from them and why we need it

**Comment by jessieay** [comment]
I think this is completed?
