### ISSUE TITLE
Admin signs in

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#840]
As an admin user, I want to go to my view immediately on login, so the system should take me to an overview page where I can see what actions I need to take

Scenario: Admin user logs in and goes to admin homepage
Given I am an admin user
When I login to the micropurchase platform
Then I should be taken to the admin actions page https://micropurchase.18f.gov/admin/action_items
And In the header I should see a link to my profile
And I should see a link to the admin home page
And I should see a link to sign out

**Comment by jessieay** [comment]
@andrewmaier thoughts on this? it's near the top of our queue now
