### ISSUE TITLE
Generating API documentation from Swagger

### ISSUE THREAD

**Issue by harrisj** [18F/micropurchase#842]
The idea is to use the [swagger.json](https://github.com/18F/micropurchase/blob/develop/public/api/v0/swagger.json) to automatically build the API documentation. This way, if we added some new functionality to the API (ie, new request endpoints or new fields), we can automatically rebuild the documentation to reflect the new structure. Currently, the documentation is [in Markdown in a separate repository](https://github.com/18F/micropurchase-api-docs), and it seems like the simplest course would be to regenerate the [API reference file](https://github.com/18F/micropurchase-api-docs/blob/18f-pages/_pages/api-reference.md) via a rake task that parses the JSON rather than relying on a complete but complex solution like [swagger2Markup](https://github.com/Swagger2Markup/swagger2markup).

This task would involve building some code to load the swagger JSON and output markdown. This would not have to be a complete solution, just enough to render our specific swagger.json.

**Comment by mtorres253** [comment]
@harrisj can you update the readme when you're done with this one? So that it points to the most accurate API docs?

**Comment by mtorres253** [comment]
Hi @harrisj is this done? Anything we can look at?

**Comment by harrisj** [comment]
The README was updated manually last week. I have been deprioritizing this in favor of other issues and PR review, so I am not close to demonstrating it yet. I would suggest that we move it to the icebox for now if we are talking about switching to single-bid auctions, since that will remove the biggest use case for the API

**Comment by jessieay** [comment]
This was merged yesterday. On prod at https://micropurchase.18f.gov/api
