### ISSUE TITLE
Fix logic on action items page

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#860]
Right now, we have "payment needed" and "payment pending" sections

payment needed:

- delivery due date expired
- delivered
- accepted
- c2 NOT submitted
- not paid

payment pending:

- delivery due date expired
- delivered
- accepted
- c2 submitted
- not paid

The problem with these scopes is that in our new world, c2 proposals are submitted before an auction goes live, so nothing should be "payment needed". This also doesnt take into account auctions that are not for the 18F pcard.....so we need to change the logic

**Comment by mtorres253** [comment]
@jessieay Question: do we even need to refer to C2 at all? Seems like payment pending is that auction has been delivered and accepted, but not paid. Paid is when it's been paid. I believe for auctions using the 18F P-card, we are checking C2 to see if the auction has been paid. For other auctions, we'll need to have someone set a paid status.

**Comment by jessieay** [comment]
@mtorres253 so you want to remove the "payment pending" section?

**Comment by mtorres253** [comment]
@jessieay I think that payment pending is just accepted but not paid yet. So we can/should keep that as admins will need to know that an auction winner needs to be paid.

**Comment by jessieay** [comment]
so then should we remove "payment needed:"  ? As I described in the description of this ticket, the two sections currently contain the same logic. If we want to change one or both, we should! Otherwise, one needs to go.

**Comment by mtorres253** [comment]
@jessieay Actually, let's keep "Payment Needed" for now. Auctions that have been accepted will appear there until they've been paid. We should have a column labeled "C2 URL" and if there is one, we should show it there (so admins can check on the status). If the auction is not using the 18F p-card, then there can be a message N/A in the C2 URL column. I think that would be good for now.

**Comment by jessieay** [comment]
@mtorres253 so you want to keep both the "payment needed" and "payment pending" sections even though they will contain the same auctions?

**Comment by mtorres253** [comment]
@jessieay Nope. Get rid of the payment pending and just peek payment needed

**Comment by jessieay** [comment]
@mtorres253 got it!
