### ISSUE TITLE
Redirects not working after login

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#873]
If someone tries to place a bid when logged out, that person should be asked to sign in and then redirected to the "confirm bid" page. This logic is not working. Instead, the person is asked to sign in and is redirected to the home page.

**Comment by jessieay** [comment]
Update: I realize this is not working because we have a `request.get?` check around our `store_referrer` logic. Wonder how we can make this a better experience for users...

**Comment by harrisj** [comment]
I am not sure why we have that request.get? guard except for the idea that we shouldn't redirect from a post (I don't think that is supposed to be common but not impossible). Any objection to just removing the guard?

**Comment by jessieay** [comment]
@harrisj it doesn't work when you remove the guard because the redirect needs to also contain the params for the bid (eg: amount) and I think what happens is that the params are not preserved...

**Comment by jessieay** [comment]
another thought on this: the only time you'd be redirected on a POST is when placing a bid. We show the bid-box to non-logged in users to entice them to sign up. Perhaps in future iterations we will not do this and will instead show a message saying "hey, if you sign up you can bid" cc @mtorres253

**Comment by jessieay** [comment]
Jacob and I discussed this and it seems like we may remove the bid box for non-signed in users in the future so in that case we won't have this issue where sometime tries to bid when not logged in and then they log in and the bid is not valid. @andrewmaier what do you think? are we going to entice non-authenticated users to bid in future designs?

**Comment by harrisj** [comment]
I suggest we have LOGIN TO BID NOW in blinking text for non-logged in users

**Comment by jessieay** [comment]
@harrisj `blink` tag?

**Comment by jessieay** [comment]
ok this is not going to be an issue in future designs so I am closing this!

**Comment by andrewmaier** [comment]
Sorry for the belated reply, @jessieay! You're correct that we won't show the form at all to logged out users.
