### ISSUE TITLE
Allow non-default purchase card auctions to be published

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#878]
This is combination UI improvement and bug fix.

Right now, we have logic in `app/view_models/admin/edit_auction_view_model.rb` that allows an admin to set an auction to `published` *only* if `c2_approved_at` is present. But this field will never be present for auctions for `purchase_card: :other` because those auctions do not have a c2 proposal to be approved.

Pieces of this story:

1. Allow an admin to publish an auction on edit without requiring a value for `c2_approved_at` when the auction is for a `other` purchase card.

2. Add validations at the `ActiveRecord` level that ensure auctions for the `default` purchase card that do not have a  `c2_approved_at` timestamp cannot be published

3. UI improvement to dynamically allow `published` if the `other` purchase card option is selected in the form.

Assuming an auction does *not* have a value for `c2_approved_at`, these are the following states available in the form (for a new auction or when editing):

State 1:

![screen shot 2016-07-14 at 3 41 30 pm](https://cloud.githubusercontent.com/assets/601515/16858112/6fa2a16e-49d9-11e6-9959-713ac6ee3086.png)

![screen shot 2016-07-14 at 3 41 48 pm](https://cloud.githubusercontent.com/assets/601515/16858117/79d9aa42-49d9-11e6-93b2-f00797d60bc5.png)

State 2:

![screen shot 2016-07-14 at 3 39 56 pm](https://cloud.githubusercontent.com/assets/601515/16858087/3cfa4c62-49d9-11e6-9c08-523ea9c36fde.png)

![screen shot 2016-07-14 at 3 41 05 pm](https://cloud.githubusercontent.com/assets/601515/16858106/62da8154-49d9-11e6-9f58-44164dff6738.png)

 This will require a little bit of jquery. 

## General Acceptance Criteria
Does not decrease code climate grade
Tests run on Travis-CI and do not break the build.
New features do not degrade accessibility (use pa11y/HTML Code Sniffer).
New functionality is adequately documented.

**Comment by mtorres253** [comment]
@jessieay @harrisj @adelevie We are going to run this as a micropurchase. I'll leave it in the backlog though

**Comment by saastree** [comment]
@jessieay Hi! We are working on this issue now. So, it seems like c2_approved_at is now c2_status. Can you confirm? Thanks!

**Comment by jessieay** [comment]
Hello! We removed the `c2_approved_at` timestamp so yes you will be looking for a `c2_status` of `:approved` -- sorry that this was out of date! we wrote it a little while ago

**Comment by saastree** [comment]
No worries. Thanks for the quick response!
