### ISSUE TITLE
Visitor and vendor messaging - Auction closed - Auction show page

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#925]
Given I am a visitor to the site, I want to see clear messaging on when bidding has closed on an auction so that I know that I don't need to be concerned about bidding on it.

- [x] **Scenario: Logged out visitor sees messaging on show page that bidding has ended for an auction**
- Given I am a visitor to the site (not authenticated)
- And there is a published auction that has passed its end date
- When I view the show page for that auction
- Then I should see the following messaging in the status box

> Bidding closed
> Bidding for this auction closed on [auction.closedDate].

<img width="330" alt="screen shot 2016-08-08 at 10 51 41 am" src="https://cloud.githubusercontent.com/assets/100149/17485038/6f491358-5d5a-11e6-9097-b6fc8c34683a.png">

- [x] **Scenario: Vendor who has not bid sees messaging on show page that bidding has ended for an auction**
- Given I am an authenticated vendor
- And there is a published auction that has passed its end date
- And I have not bid on that auction
- When I view the show page for that auction
- Then I should see the same messaging as a logged out visitor

- [x] **Scenario: Vendor who has been outbid sees messaging on show page that bidding has ended for an auction**
- Given I am an authenticated vendor
- And I have bid on an existing auction
- And the auction has ended (end date is in the past)
- And I did not win
- When I go to the show page
- Then I should see the following messaging in the status box

> Closed
> Bidding for this auction closed on [auction.closedDate]. Your bid ($[auction-bid-amount]) was not the lowest bid. Better luck next time!

<img width="331" alt="screen shot 2016-08-08 at 3 07 24 pm" src="https://cloud.githubusercontent.com/assets/100149/17492447/dee3e156-5d79-11e6-8357-414233b67cd0.png">

**Comment by andrewmaier** [comment]
@mtorres253 I updated the copy on the last one!
