### ISSUE TITLE
Create new auction flow - default p-card

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#930]
This story depends on #878

As an admin, I want the system to tell me/show me how to publish an auction that uses the default p-card payment method. So the system should show/tell me.

**Context**
Given I am an authenticated admin

- [x] **Scenario: Admin create new auction using default p-card, and sees correct messaging on show page**
- And I am on the create new auctions page
- And the auction I'm creating uses a default p-card
- And there are no errors
- When I click on the "Create New Auction" button
- Then the auction should be saved
- Ans I should be taken to the auction show page (https://micropurchase.18f.gov/admin/auctions/[id])
- And I should see a message

> C2 approval required
> This auction will be paid for using an 18F purchase card, which cannot be used without first being granted approval in C2.

- And I should see a "Request C2 Approval" button

<img width="334" alt="screen shot 2016-08-03 at 2 35 26 pm" src="https://cloud.githubusercontent.com/assets/100149/17382811/a4ae5cfa-5987-11e6-8f92-d3fa0ed78602.png">

- [x] **Scenario: Admin requests approval for new auction using default p-card by clicking on Request C2 Approval button**
- And there is a created auction that has not already had a C2 approval request made
- And I am on the show page for that auction
- When I click the "Request C2 Approval" button
- Then the system should send the C2 approval request
- And I should see that the C2 Approval is "Pending"
- Then I should see in the status box the following message

> Pending C2 approval
> This auction has been sent to C2 for approval.

<img width="338" alt="screen shot 2016-08-03 at 2 38 26 pm" src="https://cloud.githubusercontent.com/assets/100149/17382879/0f282b06-5988-11e6-9cda-997b982181bb.png">

- [x] **Scenario: Admin sees C2 Approval Pending message on auction show page - C2 URL exists**
- And there is an auction that is pending C2 approval
- And there is a C2 URL for the request
- When I go to the show page for that auction
- Then I should see in the status box the following message

> Pending C2 approval
> This auction has been sent to C2 for approval. You can check on the status here.

- And "here" should link to the C2 request URL

<img width="338" alt="screen shot 2016-08-03 at 2 38 26 pm" src="https://cloud.githubusercontent.com/assets/100149/17382879/0f282b06-5988-11e6-9cda-997b982181bb.png">

## Notes
- Question: What to do if someone changes the payment method after the C2 request is made?

- Screenshot of full page layout
![Uploading Screen Shot 2016-08-03 at 2.40.29 PM.png…]()

**Comment by jessieay** [comment]
we need a state here for "request was made and is pending" (no c2 url yet)
