### ISSUE TITLE
Admin header nav upate

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#933]
As an admin I want to see a clear navigation structure that lets me know where I can go in the site to do what things so there should be a prominent navigation in the header that is on every page.

Prototype (see notes below): https://pages.18f.gov/micropurchase/

- [x] **Scenario: Admin sub-navigation**
- Given I am an authenticated admin
- When I view any page on the micropurchase site
- Then I should see a header navigation
- And it should include a link labeled < Label >
- And that link should take me to < Destination >

| Label | Destination |
| ----- | ----- |
| Auctions | https://micropurchase.18f.gov/admin/auctions |
| People | https://micropurchase.18f.gov/admin/people |
| Settings | https://micropurchase.18f.gov/admin/settings |
| My Profile | https://micropurchase.18f.gov/profile |
| Logout | https://micropurchase.18f.gov/ (logged out view) |

## Notes
Use the labels/links in this story as some of them are missing in the prototype. Also, the prototype assumes that the vendor view and admin view are at the same URL, this does not have to be the case

**Comment by jessieay** [comment]
this was completed -- closing
