### ISSUE TITLE
Sign-in/sign-up not working on staging

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#938]
To duplicate
Go to https://micropurchase-staging.18f.gov/

Click on the sigin-in or sign-up link

Expected behavior: You should go to the sign-in or sign-up flow

Actual behavior: GitHub 404 Error
![screen shot 2016-07-22 at 12 58 49 pm](https://cloud.githubusercontent.com/assets/100149/17069623/8b6cc792-500c-11e6-9242-16181d8bb028.png)

**Comment by jessieay** [comment]
I am seeing the same thing. @adelevie can you visit https://github.com/settings/applications and confirm that the keys and match what we have on staging?

**Comment by jessieay** [comment]
This is related to the buildpack changes I made. we were using something outdated (https://github.com/ddollar/heroku-buildpack-multi) but changing to newer broke our cf-env-parser stuff, which sets ENV vars like github auth client id and secret

**Comment by jessieay** [comment]
Fix: https://github.com/18F/micropurchase/pull/943
