### ISSUE TITLE
Top level diagram of system architecture

### ISSUE THREAD

**Issue by adelevie** [18F/micropurchase#94]
![img_20151118_142402](https://cloud.githubusercontent.com/assets/86790/11251673/5b883e18-8e00-11e5-9c19-a7f2ff76c939.jpg)

**Comment by NoahKunin** [comment]
@adelevie There's no VPN - did you mean VPC?

**Comment by NoahKunin** [comment]
Also, because this is a CF/cloud.gov app, the public doesn't access the Rails app directly - the public talks to the CF Router.

**Comment by NoahKunin** [comment]
For those coming here in the future and wondering what I'm talking about, this slide presentation should clear it up: http://www.slideshare.net/cdavisafc/cloud-foundry-technical-overview [cloud.gov runs on Cloud Foundry on AWS]

**Comment by adelevie** [comment]
I'll make a new illustration. What is the boundary between what the
Micropurchase side should document and what I can omit since it's stock
CloudFoundry?

**Comment by NoahKunin** [comment]
Beyond the router (which is more for others in the future, I know it's
there of course) - you don't need to draw CF systems beyond a top
level label unless you're using CF marketplace services, which you should
box out. Example: are you running your own Postgres or CF marketplace
Postgres?

On Wednesday, November 18, 2015, Alan deLevie <notifications@github.com>
wrote:

> I'll make a new illustration. What is the boundary between what the
> Micropurchase side should document and what I can omit since it's stock
> CloudFoundry?
>
> On Wednesday, November 18, 2015, Noah Kunin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > For those coming here in the future and wondering what I'm talking about,
> > this slide presentation should clear it up:
> > http://www.slideshare.net/cdavisafc/cloud-foundry-technical-overview [
> > cloud.gov runs on Cloud Foundry on AWS]
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/18F/micropurchase/issues/94#issuecomment-157902290>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/micropurchase/issues/94#issuecomment-157903344>.
>


-- 
Noah Kunin
18F Infrastructure Director | @18F <https://twitter.com/18F>

**Comment by adelevie** [comment]
@NoahKunin here is the updated top-level diagram:
![img_20151119_164243](https://cloud.githubusercontent.com/assets/86790/11285311/d322cc36-8edc-11e5-8700-43b26082c192.jpg)

**Comment by harrisj** [comment]
Can we close this since Micropurchase has its ATO?

**Comment by NoahKunin** [comment]
Yep. Weird I'm assigned.
