### ISSUE TITLE
Admin Auctions - Needs Attention/Delivery needed

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#947]
As an admin I want to quickly see which auctions that need delivery, so when I go to the "Needs Attention" page, I should see them 

**Context**
- Given I'm an authenticated admin
- When I'm on the Needs Attention page 

- [x] **Scenario: Admin sees a "Delivery needed" section on Needs Attention page**
- Then I should see a section labeled "Delivery needed"

- [x] **Scenario: Admin sees auctions that need delivery on the Needs Attention page**
- Given there are auctions that are published
- And those auctions have ended
- And the auctions have winning vendors
- And the auction end date has passed
- And the auction has not yet been marked as delivered by the vendor
- When I look at the Needs Attention page
- Then I should see these auctions listed in the "Delivery needed" section
- And for each auction, I should see a column labeled < Column Name >
- And for each auction, I should see < Data > in that column

| Column Name | Data |
| ----- | ----- |
| Title | Auction Title |
| Delivery Deadline | Days/hours to delivery deadline, or Days/hours past delivery deadline |
| Delivery URL | The Delivery URL or N/A |
| Winning Vendor | Vendor Name |
| Edit | Edit link |

- [x]  **Scenario: Admin sees message that there are no auctions needing delivery**
- Given there are no auctions needing delivery
- When I'm on the "Needs Actions" page
- Then I should see a message "There are no auctions needing delivery" in the "Pending Delivery" section

- [x] **Scenario: Admin clicks on auction title and navigates to auction show page**
- When I click on the title of the auction needing delivery
- Then I should go to that auction's show page

- [x] **Scenario: Admin clicks on edit link and navigates to auction edit page**
- When I click on the edit link of the auction needing delivery
- Then I should go to that auction's edit page

**Comment by jessieay** [comment]
@mtorres253 under what conditions do we put each of these statuses: 

"Delivery Pending", or "Delivery Past Due"

if it is just based on delivery deadline, this seems redundant since we also have delivery deadline in the table as a relative value (eg: 1 day ago)

**Comment by jessieay** [comment]
This added the section: https://github.com/18F/micropurchase/pull/1073/commits

Will keep this open until above questions i resolved

**Comment by jessieay** [comment]
hey @mtorres253 question for you on this (see comments)

**Comment by mtorres253** [comment]
Delivery pending:
- Given there are auctions that are published
- And those auctions have ended
- And the auctions have winning vendors
- And there is not yet a delivery URL
- And the auction end date has passed
- And the auction has not been accepted or rejected

Delivery past due
- Given there are auctions that are published
- And those auctions have ended
- And the auctions have winning vendors
- And there is not yet a delivery URL
- And the auction delivery deadline
- And the auction has not been accepted or rejected

**Comment by mtorres253** [comment]
Right now I'm seeing a draft auction in the pending payment section so I added the condition that the auction be published

**Comment by jessieay** [comment]
> Right now I'm seeing a draft auction in the pending payment section so I added the condition that the auction be published

screenshot / link? not sure what you mean by this, I am not seeing it. Also, this issue is for "pending delivery" so perhaps for a separate GH issue?

> what about an auction that *does* have a delivery URL but is past due?

Michael : Yes that would be in pending delivery

> What do we put in 'status' for delivery url present but hasn't been marked as done?

**Comment by jessieay** [comment]
I think it makes sense to include any auction that ended and has not been marked as “done” in pending delivery, we just want to know what “status” to have for the 4 possibilities:

- auction has no delivery url, not past due
- auction has no delivery url, past due
- auction has delivery url, not past due
- auction has delivery url, past due

**Comment by mtorres253** [comment]
We can add that in a future story. For now, let's stick to "Delivery Pending" for auctions with a delivery URL that have not been marked as delivered

**Comment by mtorres253** [comment]
For screenshot look at comment above

**Comment by jessieay** [comment]
but then we wont have any way for an admin to see auctions without a delivery url in the needs attention page -- doesnt that seem problematic?

**Comment by jessieay** [comment]
screenshot above is from "pending delivery" but you said "pending payment" -- I am confused!
