### ISSUE TITLE
Open auction messaging - vendor/sealed-bid

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#954]
As a vendor, I want to quickly get high-level information about the status of any open auction so that I don't have to derive it from looking at the auction details, and so that I can take action.

Prototype (see notes): https://pages.18f.gov/micropurchase/auctions/show/
(Select Auction Status: Published (Open), User: Vendor)

**Context**
Given I am a registered vendor
And there is an auction that is sealed-bid
And the auction is open (start date has passed, end date is in the future)

- [x] **Scenario: Vendor who has bid on a sealed-bid auction sees status message in the bid box**
- And I have bid on the auction
- When I go to the auction show page
- Then I should see this message in the bid box

> You bid $[vendor's bid amount] on [mm/dd/yyyy, hh:mm ET].

- [x] **Scenario: Vendor who has NOT bid on a sealed-bid auction sees status message in the bid box, and bid form**
- And I have NOT bid on the auction
- When I go to the auction show page
- Then I should see this message in the bid box

> This auction is accepting bids until [auction.endDate]. The maximum bid for this auction is [starting price - bid increment]

- and I should see a text input
- and I should see a button labeled "Place Bid" next to it

https://pages.18f.gov/micropurchase/auctions/show/?auctionWorkflowState=published-open-bid-rejected-vendors

# Note:
- Use the copy in the requirements. Consult @andrewmaier with any layout questions.

**Comment by jessieay** [comment]
@mtorres253 thoughts on making language for those who haven't bid consistent with the messaging for reverse auctions:

> The maximum bid for this auction is [starting price - bid increment]

?
