### ISSUE TITLE
Show how much money has been saved by the Micro-purchase platform

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#964]
As a member of leadership at 18F, I'm trying to quantify how much much money we are saving the government due to our efforts, so since micropurchase measures the savings resulting from each auction, we should have an easy way to show the total savings generated by this platform

- [ ] **Scenario: I see total savings generated by the micropurchase platform on the insights page**
- Given I am a visitor to the Micro-purchase site
- When I am on the insights page
- Then I should see a section labeled "Total Savings"
- And in that section I should see the total savings generated by the platform for all successful auctions

Total Savings = sum of all starting prices for successful auctions - sum of all awards for successful auctions

## Notes
I would put this in a row below the last row of high-level stats. Just underneath average starting price. We can clean up the design later

**Comment by jessieay** [comment]
@mtorres253 in what order do you want this stat and what should the text say?

**Comment by mtorres253** [comment]
updated @jessieay

**Comment by jessieay** [comment]
ok! all of the other labels are lowercase so going to do that here, too
