### ISSUE TITLE
Vendor workflow and messaging - Auction show page - Bid on auction

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#985]
As a vendor, I want to see clear messaging around whether my bid was accepted or not (in either type of auctino), so the system should show me

**Context:**
- Given I am an authenticated vendor
- And there is a sealed-bid auction
- And I am qualified to bid on that auction
- And I am on the auction show page (micropurchase.18f.gov/auctions/[id])

- [x] **Scenario: Vendor sees javascript bid confirmation after placing bid - sealed-bid**
- And I have NOT bid on the auction
- And I have entered a bid amount in the bid box
- When I click the "Place Bid" button
- And there are no errors
- Then I should see a javascript confirmation popup

> micropurchase.18f.gov says
> Are you sure you want place a bid for $[bid_amount]?

![screen shot 2016-09-02 at 10 50 23 am](https://cloud.githubusercontent.com/assets/100149/18213148/92334d70-70fb-11e6-8d88-3aedfa8ebe98.png)

- [x] **Scenario: Vendor confirms bid - sealed-bid**
- When I click on the "OK" button in the javascript confirmation
- And there are no errors
- Then my bid should be placed
- And I should see a success message

> Bid placed
> You placed a bid of $[auction.currentBid] on [auction.bidDate].

<img width="332" alt="screen shot 2016-08-08 at 2 48 27 pm" src="https://cloud.githubusercontent.com/assets/100149/17491911/94f87b26-5d77-11e6-8a24-7dae5b4a391c.png">

- [x] **Scenario: Vendor cancels out of javascript confirmation - sealed-bid**
- When I click on the "Cancel" button in the javascript confirmation
- Then my bid should not be placed
- And the javascript confirmation box should close

**Comment by jessieay** [comment]
- green styles needed
- make sure this is working for sealed and multi-bid

**Comment by harrisj** [comment]
Oops, my bad on the styling
