### ISSUE TITLE
Move copy to i18n

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#996]
See https://github.com/18F/micropurchase/pull/993#discussion_r73394035

**Comment by mtorres253** [comment]
I love this idea @jessieay and I think it would make it easier for us to adjust the copy (we won't have to bug you to do it)

**Comment by mtorres253** [comment]
Maybe we should do this now before all the other status messaging stories?

**Comment by jessieay** [comment]
sure we can prioritize this!

**Comment by mtorres253** [comment]
Cool @jessieay It's at the top of the backlog. We can discuss at planning on monday.

**Comment by mtorres253** [comment]
@jessieay is doing this in pieces, so touch base with her @harrisj and @adelevie to see if there are any pieces you want to take on

**Comment by mtorres253** [comment]
This is an ongoing thing and everyone is aligned on this refactoring. When we refactor other parts of the project, we implement this. Closing this issue for now
